### ISSUE TITLE
Filepicker

### ISSUE THREAD

**Issue by knekke** [xavier150/Blender-For-UnrealEngine-Addons#1]
Hi,

just stumbled upon your addon. 
In case you want to replace the path copy&paste process with a filepicker:
https://github.com/20tab/UnrealEnginePython/blob/master/examples/slate_file_path_picker.py

cheers,
Thomas

**Comment by xavier150** [comment]
Hi ! 
Thank you but it's not code that I can implement in blender, because it's a code for UnrealEnginePython, it should directly enter all the code to open the picker instead of simply copy the line in Unreal ^^ 
(Sorry for my english)

Xavier

**Comment by knekke** [comment]
It was ment to be for the Unreal import part. In the demovideo it looks like you are copy&pasting paths from the explorer to the unreal commandline, where you could use a  filepicker instead. Didn't mean to cause any confusion :)
