### ISSUE TITLE
Will not allow enabling addon. Syntax error. 

### ISSUE THREAD

**Issue by ultramoonie** [xavier150/Blender-For-UnrealEngine-Addons#10]
Version: Blender 2.79
Addon Version: 0.2.2.2

When selecting the check box to enable the 'Import-Export: Blender for Unreal Engine' add on error reads: 
File: ..... addon_utlis.py", line 331, in enable mod = _import(module_name)
File: ..... _init_py", line 345, name: StringProperty(name="Action data name", default="Unknown")

SyntaxError: invalids syntax

![BlenderAddonErrorReport](https://user-images.githubusercontent.com/49373489/55687734-333fec00-5925-11e9-825d-e339162783b0.jpg)

**Comment by xavier150** [comment]
Hi ultramoonie,
There are two versions of the addon for blender 2.8 and blender 2.7.
For blender 2.79 you need use [blender-for-unrealengine0.2.2c_Blender2.7.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/download/v.0.2.2c/blender-for-unrealengine0.2.2c_Blender2.7.zip) which is the latest version on this page https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v.0.2.2c
