### ISSUE TITLE
Textures and Scale of Object are not working

### ISSUE THREAD

**Issue by JamesTroici** [xavier150/Blender-For-UnrealEngine-Addons#103]
I imported the entire collection but when I put the building into Unreal it was extremely small and non of the textures worked. They either turned completely white or black and transparent

The only error I got when setting up the collection to export was that my scale wasn't in the proper form so I pressed the button that will fix it, clearing the error. When I exported this error was no longer present so I'm unsure why the scale of my building was wrong.

Are most blender texture nodes not supported when moving objects with complex textures to Unreal?

Here are some reference photos:

![image](https://user-images.githubusercontent.com/77027862/123328958-3cb7cd80-d50a-11eb-8b34-e4bae88bad87.png)

![image](https://user-images.githubusercontent.com/77027862/123329018-51946100-d50a-11eb-8c4d-873621c055c5.png)

![image](https://user-images.githubusercontent.com/77027862/123329056-5e18b980-d50a-11eb-9ed4-500df9b74d3e.png)

**Comment by xavier150** [comment]
Hello @JamesTroici 
About the Scale error maybe you speak about the scene unit scale ?
That not really an error just a warning for avoid problem with Skeletal Mesh.
More info: [Skeleton & Root bone](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/How-export-assets#skeleton--root-bone)

About textures my addon does not yet support textures import and material. You must create them in Unreal Engine and import texture.

**Comment by xavier150** [comment]
Hey @JamesTroici
I close this issue, If you still have problems you can reopen it. :)
