### ISSUE TITLE
Blender 2.92 does not add objects to export

### ISSUE THREAD

**Issue by mtschatz** [xavier150/Blender-For-UnrealEngine-Addons#104]
I am trying to use the "Blender-For-UnrealEngine addon in Blender 2.92, and I am having a problem with getting my objects to export. I had placed all of my objects in a collections folder, and I tried the following....

steps to reproduce:

Export Collection:
1. select all of the objects to be exported.
2. in object mode, press the "m" key to make or move the selected objects to a collection group
3. under global properties, click on the "scene tab."
4. if no collections are not listed, the click on "update collection list," and then place a checkmark on the collection(s) to be exported. I selected 1 collection, and it reported 1 collection(s) will be exported.

5. down below the collection list, the addon should report the number of collection to be exported.
6. next line down, paste the folder path for the objects to be saved to.
7. I am not sure if you need all export properties ticked, but I selected, "Static Meshes," "Collection(s)," "Export Log," "Import Asset Script," and "Additional data."
8. under Assets exported, in my case, there should be 21 objects, but the addon is reporting 1 assets will be exported.
9. Despite it stating 1 asset will be exported, I still clicked on export, thinking maybe it says this because I am exporting a collection instead of individual objects." Doing so, caused the addon to save an empty FBX file. I tried opening the file in Windows 10 3d viewer, and sure enough nothing is shown.

By Object:

With this method, setting the export method to selected produces this...
1. select all of the objects to be exported. in my case, once again, I selected 21 objects but the addon reports 0 asset(s) will be exported
2. I still clicked on export anyway, but I get an error stating, Not found assets with "Export recursive" properties or collection to export.
3. However, choosing no filter, reports 1 asset will be exported and it should be 21. Furthermore, opening the file in Windows 10 3d viewer displays all 21 objects as 1 object, but I need them to be individual objects. I need to export as individual objects because I am using them as modular pieces.

also, I tried adding the blend file to this attachment, but GitHub says it does not support *.blend files

**Comment by mtschatz** [comment]
I forgot to mention this problem is happening in the addon version 2.9, which your fixed log says it is fixed. So unless I am using it wrong, this is technically not fixed.

**Comment by xavier150** [comment]
Hey @mtschatz !
It is normal that the addon displays only one Assets and not 21. Exporting with collection will only export your collection like a StaticMesh.
Doc: [Export collection like a StaticMesh](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/How-export-assets#export-collection-like-a-staticmesh) | 
Example with collections: [City parts in collections](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/Examples-files#city-parts-in-collections)

On the other hand the file should not be empty, it can be an error of the addon. You can send me the file? 
Try to put the file in a .Zip File


About "Export only select" in export panel is just a filter of the assets to export. I will change the text in the next version to make it easier to understand

About individual objects and modular pieces the best is set the Export type property to "Export recursive" on all object you want to export so the addon know what to export.
I do a tuto vidéo about modular assets, that can help you.

Video: [How Import Blender assets to Unreal Engine](https://www.youtube.com/watch?v=2ehb2Ih3Nbg)
Doc: [Prepare assets to export](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/How-export-assets#prepare-assets-to-export)

**Comment by xavier150** [comment]
Hey @mtschatz You still have issues? I not received file.
If not you can close this issue. :)
