### ISSUE TITLE
LogPython Error

### ISSUE THREAD

**Issue by Toharik** [xavier150/Blender-For-UnrealEngine-Addons#108]
Hi!
First off thanks for writing this addon, but I ran into a problem when using it.
I'm trying to transfer cameras into UE4 from blender 2.93.
After pasting, an error appears:
[
![Screenshot_1](https://user-images.githubusercontent.com/67224266/124894673-89100c80-dfe4-11eb-96e6-ab48e9f16c00.png)
](url)

Can you tell me what it may be related to?

**Comment by xavier150** [comment]
Hey @Toharik 
Thanks for the report.
I will look about when I come back to home.
Waiting maybe you can try with a previous version ?

**Comment by Toharik** [comment]
Tried it, it doesn't work

**Comment by xavier150** [comment]
Hey @Toharik
I wasn't able to reproduce this issue, you use what version of UE4?
And you can send my the file? I will try on my side.

**Comment by Toharik** [comment]
Hey @xavier150 
I use UE4 version 4.24.3
Yes, i can. I sent the file to your email.

**Comment by Toharik** [comment]
Hey @xavier150 
I use UE4 vwesion 4.24.3
I mailed you the file.

**Comment by xavier150** [comment]
@Toharik Thanks I reproduce and fixed the issue!
That because Unreal Engine 4.24 use Python 2.7 and not Python 3 so the code is not the same for the both version.
I updated the dev Branch: [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch)

**Comment by Toharik** [comment]
Hey @xavier150 
Hmmm
Maybe I'm doing something wrong, but the error remains...

**Comment by xavier150** [comment]
You try the Dev Branch? You get exactly the same error at the line 34?

**Comment by xavier150** [comment]
Hey @Toharik you still have this error?
You can try v0.3.0 - Preview 1 too https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/vp0.3.0
