### ISSUE TITLE
Collections export with random names (?)

### ISSUE THREAD

**Issue by Hevedy** [xavier150/Blender-For-UnrealEngine-Addons#109]
![UE4Editor_2021-07-09_14-15-46](https://user-images.githubusercontent.com/3521442/125076701-8682e500-e0c0-11eb-95d9-c2b83d2bd064.png)
Today trying to use the import level from fbx feature noticed at re-export from Blender to the same file and reimport at ue4 the group name changes the index and the group name isn't the one I set inside Blender.

**Comment by xavier150** [comment]
Hey @Hevedy 
Thanks for the report!
I will look about when I come back to home in a week.

**Comment by Hevedy** [comment]
Actually after update to the last version of the plugin got it even worst like:
![UE4Editor_2021-07-09_16-39-54](https://user-images.githubusercontent.com/3521442/125095358-62310380-e0d4-11eb-9421-310c15c5139b.png)

Tried editing the line 9X from the file "bfu_export_single_static_mesh_collection.py"
Can set the name of the collection to something like Name + "_Export" or + "Collection"
But for some reason now set to the meshes names the whole URL

**Comment by xavier150** [comment]
Hey @Hevedy, 
I'm Back to work, I changed the export method for collection. That should be better, you can try the last dev Branch: [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch)

**Comment by Hevedy** [comment]
Thank you, will try it tomorrow or early the next week.

Thanks!

**Comment by jeffhoral** [comment]
Hey there I think i might have a similar problem - The Collections List shows up blank in Blender 2.83.3 and I can't select which collection to export. I also get an error in the blender log that says like "Traceback file blender\addons\blender for unreal\bfu-ui.py", line 1133 in draw item Icon: "OUTLINER_COLLECTION"

![collectionproblem](https://user-images.githubusercontent.com/88950975/129462232-20af78c9-5ea3-4973-b959-03588dad9368.jpg)

Any ideas?
Thanks!

**Comment by jeffhoral** [comment]
Nvm! I just updated everything and it's working fine now :-)
