### ISSUE TITLE
Collision naming convention invalid for UE4

### ISSUE THREAD

**Issue by nspidel** [xavier150/Blender-For-UnrealEngine-Addons#11]
I've always had difficulty getting collision names to work in UE4, but the one naming convention that always works without fail is to 100% of the time include two digits in the suffix, even if they are zero. "CollisionType_ObjectName_xx"

This is in line with Unreal's documentation regarding the FBX static mesh pipeline.
https://docs.unrealengine.com/en-us/Engine/Content/FBX/StaticMeshes

As it is, with your addon I have about a 20% success rate when, by chance, it decides to write in a valid suffix during the export. Perhaps I have other settings that are incorrect. Regardless I would definitely like to see the _xx suffix, it's more reliable, and adhere's to UE4's documentation.

**Comment by xavier150** [comment]
Hello nspidel !
Thanks, I would make the change, but this is also supposed to work with a single suffix. 
I think this is due to another problem, can you send me the file with the collisions fail ?

**Comment by nspidel** [comment]
Ah... Shoot, I actually can't send you this file. It's a work file and it's all NDA.

**Comment by nspidel** [comment]
I just got it to work! So.. my collisions do not seem to update when I reimport the models. I need to make my changes, delete my meshes from the UE4 project, and then when I import them the changes are visible. So I think you're right, it may not have anything to do with the collision names (although it'd still be nice if their names were all _xx in Blender, lol just for my own personal OCD reasons, but that's not important lol) but maybe it has to do with the importer? Scripts and programs really are not my thing at all, but I hope I can help you hone in on your debugging! It's a great addon

**Comment by xavier150** [comment]
The collision is supposed to be updated also with the reimport without having to use the import scripts, 
http://xavierloux.com/sharex/CollisionUpdate.gif
The name of your object may contain spaces or illegal characters, you work with which version of unreal?
Thanks !

**Comment by nspidel** [comment]
I'm using version 4.21
And my naming convention should be completely legal. I use "-" instead of spaces, and I only use letters and numbers.

It's so bizarre, sometimes I can get collisions to work, and, in the case of this model, the collisions appeared when I imported them the first time. Every single export/import after that initial successful attempt has failed to generate collision meshes.

1) Export and import model successfully
2) Make modifications
3) Can no longer export or import model

![image](https://user-images.githubusercontent.com/10458682/56626484-d70ce580-660f-11e9-80bd-6fc70360d78b.png)

**Comment by nspidel** [comment]
These are the settings for my meshes
![image](https://user-images.githubusercontent.com/10458682/56626588-47b40200-6610-11e9-9e4b-cd34bb023cba.png)

These are the settings for my collision meshes
![image](https://user-images.githubusercontent.com/10458682/56626608-5c909580-6610-11e9-844a-dc8a0c12ae26.png)

**Comment by nspidel** [comment]
This is probably my 30th attempt to export/import this particular model. It was successful. What I had to do was manually reassign each collision mesh to its object. I did take note that it reset all of the names to not include a _# suffix unless it is in a series of 2 or greater collision meshes. Which still leads me to believe that this is a naming convention problem, and perhaps could be solved by always including a _## suffix as suggested in the UE4 documentation, and is my personal practice. If there's only one collision mesh, do not include a suffix (or, alternatively, just include a _00, which Unreal seems to be okay with), and if there are two or more collision meshes, count up from _00, _01, _02

**Comment by xavier150** [comment]
Hi nspidel, sorry for the delay

According to your parameter and object names this should work fine. I think it's a problem with your version of Unreal, can you try to reinstall your Unreal 4.21 with config and save or test with another version and on an empty project?

I have do a version with _## as suffix for test: 
[blender-for-unrealengine.0.2.3(test)_Blender2.7.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/3130264/blender-for-unrealengine.0.2.3.test._Blender2.7.zip)
[blender-for-unrealengine.0.2.3(test)_Blender2.8.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/3130265/blender-for-unrealengine.0.2.3.test._Blender2.8.zip)
it's not version 2.3, just a test but in your case it will be able to solve the problem, tell me if it works better
