### ISSUE TITLE
UE5 content browser does not display files

### ISSUE THREAD

**Issue by TalonEmery** [xavier150/Blender-For-UnrealEngine-Addons#112]
I want to import the camera of Blender. After I use the plug-in to enter the code into UE5, the file is not displayed in the content browser
![ue5](https://user-images.githubusercontent.com/87163077/125879493-07f32251-156f-4f66-ac22-14e6f9e9cc59.png)

**Comment by xavier150** [comment]
Hey @TalonEmery
You enable the Python plugins in Unreal Engine ?

![ImportAssetDocVaniaPython.jpg](https://user-images.githubusercontent.com/7216958/125914865-8116c77c-4358-4570-8d82-460fa1b00fd7.jpg)

**Comment by TalonEmery** [comment]
> 嘿@TalonEmery
> 你在虛幻引擎中啟用了 Python 插件嗎？
> 
> ![ImportAssetDocVaniaPython.jpg](https://user-images.githubusercontent.com/7216958/125914865-8116c77c-4358-4570-8d82-460fa1b00fd7.jpg)

![image](https://user-images.githubusercontent.com/87163077/125917286-a29da447-a80a-4547-a8ff-567c2ab74be7.png)
Yes

**Comment by xavier150** [comment]
You can send me the file? I will try to found what wrong

**Comment by xavier150** [comment]
Hello @TalonEmery 
You still have this problem ?
