### ISSUE TITLE
Camera Export Animation Mismatch

### ISSUE THREAD

**Issue by HiteshDubey007** [xavier150/Blender-For-UnrealEngine-Addons#114]
Have tried the Addon couple of times and It gave few Different results in different tests.

1:- In a basic Random camera animation it worked perfectly. But When I animated another Camera with Proper timing as per my requirement, It got Exported But the Frame count(Rendering range/Shot Range)  was Different than what was set in Blender. In my Blender file the Frame count was 570 frames but inside UE4.26 the sequence created via CMD was only 130 Frames.(Also the Camera was mismatch)

2:- With few Tests and few other Exports, The frame count got sorted automatically but, when I Checked the Camera animation it was Different(like an offset) than what was in Blender.

3:- Suggestion, Please Mention in Your Tutorials and in Manual/Documentations that, it is compulsory to add a marker for Camera export especially. I spent more than 45 minutes struggling with it and finally got to know adding marker is the only way(Which I know) to export camera.

**Comment by xavier150** [comment]
Hey @HiteshDubey007,
Thanks for the feedback. I Alredy do a video tutorial about Camera export: [How Import Blender camera to Unreal Sequencer](https://youtu.be/Xx_9MQu2EkM)
And you have more info in Import assets doc: [Import Blender camera to Unreal Sequencer with python](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/How-import-assets#import-blender-camera-to-unreal-sequencer-with-python)

If you have only one camera that work without Markers but with several camera you need do the cuts with Markers like the normal use in Blender

I plan to update the documentation to make it more intuitive with one page per element. Animations / Camera / LightMap / [...]

**Comment by HiteshDubey007** [comment]
Thanks for the Reply. 
I have already seen the videos and the Docs, you have done a good job on it. Can you please tell me how can I export a full scene with animated camera animated objects etc. Coz I have a huge scene and to export each and every object by selecting and assigning it in exporter is quite time consuming. Can you help with this please.

**Comment by xavier150** [comment]
Hey @HiteshDubey007, Sorry for the delay.
Unfortunately you will have to do at hand. For static objects you can export collection. This allows to easily organize the export of a lot of element in a simple Static Mesh. For animated objects you need use a Rig and export like a Skeletal Mesh.

For remove assets from the export list you need select the object and assigning the export type on Auto or Not Exported.
The minus or cross sign is a good idea. I think too add a button for select.

**Comment by xavier150** [comment]
Hey @HiteshDubey007 I just made the connection with what you said. "it is compulsory to add a marker for Camera export especially." This is a bug. I fixed and updated the Dev Branch: [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch)
- Fixed: Camera export don't work when scene has no timeline_markers.
