### ISSUE TITLE
Animation for Cameras works sometimes

### ISSUE THREAD

**Issue by jgbatu** [xavier150/Blender-For-UnrealEngine-Addons#115]
Hi, and first of all THANK YOU so much for this addon. It works better than the Send2UE addon in my opinion, so props to you!

I downloaded the Supercar blend file cause I wanted to figure out why the camera export for that file works exactly as it should, but when I create a new blend file with one camera and even add markers, the addon doesn't export any keyframe animation for the camera. But when I export from the example file you gave, it does. I spent the entire day trying to see what the difference between the two files was and I can't find anything. And I get the same result for multiple versions of the addon. I'm using Blender 2.93 and Unreal Engine 5.

So I guess my question is, Is there something special about your Supercar example blend file. I see that your cameras are parented to a camera rig armature and most of the camera animation is done via the rig bones that the cameras are location and rotation constrained to but I don't know if that is the reason it works. In unreal, it seems like all the channels for the cameras have are keyed, which makes me think that the addon did that but again I don't know.

Thanks again

**Comment by xavier150** [comment]
Hey @jgbatu, Thanks for the report and for using my addon! :)

I think that a bug. Bake Only Visible Cuts is used for optimiste the export time.
<img src="https://raw.githubusercontent.com/xavier150/Blender-For-UnrealEngine-Addons/master/docs/CamerasDocBakeOnlyVisibleCutsOffOn.jpg">
But a bug breaks the export when it cannot find a marker or when it reads them out of order.

I fixed this in the last Dev Branch [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons) I will update the addon soon.
