### ISSUE TITLE
LogPython: Error

### ISSUE THREAD

**Issue by tommywright** [xavier150/Blender-For-UnrealEngine-Addons#116]
I get the following error when trying to import in UE4 (4.26.2 and Blender 2.93)

LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "D:/Depot/BlackSands_Source/Shots/080/ExportedFbx/ImportSequencerScript.py", line 158, in <module>
LogPython: Error:     print(CreateSequencer())
LogPython: Error:   File "D:/Depot/BlackSands_Source/Shots/080/ExportedFbx/ImportSequencerScript.py", line 20, in CreateSequencer
LogPython: Error:     import ConfigParser
LogPython: Error: ModuleNotFoundError: No module named 'ConfigParser'

**Comment by xavier150** [comment]
Key @tommywright ^^
I just publish a new Pre-release who should fix the problem:
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/vp0.3.0

**Comment by tommywright** [comment]
@xavier150 YES! Your 3.0 version works perfectly. Holy mac.. thank you sooo much for this!!
