### ISSUE TITLE
Some really weird black spot that appear on the mesh

### ISSUE THREAD

**Issue by polidox2** [xavier150/Blender-For-UnrealEngine-Addons#118]
sometimes those black spot appear when i import a model.
https://imgur.com/a/hBQvpce

i am using UE5.
so i tried of course add light
build light
it just doesnt go
the texture is clean it doesnt contain this, totally clean in blender no black spots.
it just show on the viewport and when you compile the game.

**Comment by polidox2** [comment]
i tried remove the materials, and the black spot is still there with the mesh.

**Comment by xavier150** [comment]
Hey @polidox2 
You can send me the model ? I will try on my side. You using the last version ? 0.3.0 preview 1

**Comment by polidox2** [comment]
Thank you xavier for your fast reply, i am using the 0.2.9
i will try with the 0.3.0 preview 1

and here is the model:
https://mega.nz/file/0lYxAYQT#F1X1zkjxHEBAQXuqhIHo7oe_zZKHxyF05Er0t6DE5gU

**Comment by xavier150** [comment]
I tried to reproduce the error but no result. On my side that work good. It may be a rendering problem. You try in a project with native settings? I also notice that the UV is very twisted this can cause artifacts depending on the shader.

![image](https://user-images.githubusercontent.com/7216958/130263819-8b382665-b42f-4bb4-ba0e-223ce9abd42e.png)
![image](https://user-images.githubusercontent.com/7216958/130263919-5ad35187-beb5-4790-bd41-db8713286145.png)

**Comment by polidox2** [comment]
Thank you about those artifacts how to fix that? because i don't see any problem with the model in blender.

**Comment by xavier150** [comment]
If that work good with a new unreal projects you can check settings for found what produce this

**Comment by polidox2** [comment]
thank you for checking.
