### ISSUE TITLE
Export recursive: selection issue

### ISSUE THREAD

**Issue by Avolendi** [xavier150/Blender-For-UnrealEngine-Addons#119]
Bug:
When I have both a parent and a child object set to Export Recursive, then selecting the child will still also export the direct parent. I also have the option 'Only Select' active (grammar note: "selected" sounds better)
Having more hierarchy above or below doesn't matter, only the direct parent of the selected object gets included.

Using Blender 2.91.0, tool version 0.2.9 Release

**Comment by Avolendi** [comment]
Note: Had 2 bugs which I assumed related, but one may have been a mistake on my end. So changed the ticket to only reflect the confirmed one.
The other issue was likely due to not having properly box shapes for UBX collision shapes, which apparently UE4 removes silently.

**Comment by xavier150** [comment]
Hey @Avolendi 
Thanks for the note I change to "selected" ^^

About the export and select this is normal, it is to avoid having selected the root of the asset. If you select an object that is part of it then it will also be exported. It's as if you select the two assets.

![image](https://user-images.githubusercontent.com/7216958/130332128-be975f87-293d-43e5-beb9-a773b481c4f1.png)

**Comment by Avolendi** [comment]
Np. Thanks very much for the tool!
Without it I don't know how much more work I'd have getting my project in to Unreal :)

I understand the selection will search up the hierarchy, until it finds a parent which has Export Recursive set.
But should it also do that when the currently selected object already has Export Recursive set?

It seems like the intention is for anything which is marked with Export Recursive to not have a parent.
Or at least none which is also marked as Export Recursive.
Which would make fixing this optional polish, since it does contradict the intended use case.

**Comment by xavier150** [comment]
Hey, sorry for the delay I answer soon ^^

**Comment by xavier150** [comment]
Yes it is correct! It is preferable that if an object is export recursive, that there is no parent that is also export recursive.
In your case I think it is better to dissociate the two assets in different hierachys if that possible.
![Assets](https://user-images.githubusercontent.com/7216958/130465873-1c89ad3d-f8c4-4c39-b25f-ded4fb9a083b.png)

I will have to improve the documentation and wiki haha

**Comment by Avolendi** [comment]
Ah okay, thanks. Then I'll close this issue :)
This problem only appeared because I tried to get around the bug I reported.
