### ISSUE TITLE
Blender Export

### ISSUE THREAD

**Issue by renzo-caroca** [xavier150/Blender-For-UnrealEngine-Addons#121]
![2021-08-23_15-28-11](https://user-images.githubusercontent.com/52253086/130507760-fbfd07c6-73eb-4781-8427-49702f263741.png)

Message I get once I am trying to export to UE4

**Comment by xavier150** [comment]
Hey @renzo-caroca
Thanks for the report! 
This error was fixed is the last v0.3.0 - Preview 1 https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/vp0.3.0 I will release version 0.3 in not too long I think.
