### ISSUE TITLE
error that pop from nowhere

### ISSUE THREAD

**Issue by polidox2** [xavier150/Blender-For-UnrealEngine-Addons#122]
everything was working fine don't know what changed recently i am having this boring error:

![image](https://user-images.githubusercontent.com/29620611/130546969-9ebe6122-8f95-4277-98da-bdd463b5bbb7.png)

using the last version 0.3 and last version of blender.

**Comment by xavier150** [comment]
Hey @polidox2 ,
Thanks for the report! I just updated the Dev Branch [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons)
Tell me if everything is working fine now

**Comment by polidox2** [comment]
Well it's fixed, but when i export now i have this new error:
![image](https://user-images.githubusercontent.com/29620611/130683122-984d0dcb-7b47-4ddb-8934-7330290fbeb8.png)

if you can have a look please thank you

**Comment by polidox2** [comment]
Delete the last dev branch and installed the 0.2.9 no errors with it works fine.

**Comment by polidox2** [comment]
i think its better i close this and open new issue so you dont get confused.
