### ISSUE TITLE
camera export

### ISSUE THREAD

**Issue by ib3364** [xavier150/Blender-For-UnrealEngine-Addons#125]
hello sir and please don't mind my English,
whenever I tried to export the camera it exported the wrong transforms in unreal it appeared that it is scaled down in unreal for some reason I'm not sure what went wrong....please check the video provided along with the blend file
[https://drive.google.com/file/d/1ddkWIqy6hPRoUHH3fXHKY64vys2iWrZw/view?usp=sharing](url)

**Comment by xavier150** [comment]
Hello @ib3364 
There is a problem of scale. the objects in your Blender scene are much smaller than in Unreal. If you also import the two objects, the sizes are consistent 
![sizes are consistent](https://user-images.githubusercontent.com/7216958/133421319-8c565a19-9545-41e0-aaa9-766d4b5a2d73.jpg)

**Comment by xavier150** [comment]
I close this, open it again if it still doesn't work
