### ISSUE TITLE
Error while exporting armature

### ISSUE THREAD

**Issue by Gamination** [xavier150/Blender-For-UnrealEngine-Addons#126]
Whenever I export armature which as only one object as child it displays this error
Not using alembic, no constraints, no nla, only baked keyframes, no bouncy bones or anything like that

![Screenshot_839](https://user-images.githubusercontent.com/79735403/132942848-a6620e17-c429-411a-9b6a-15e1aef54c08.png)

**Comment by xavier150** [comment]
Hey @Gamination, Sorry for the delay and thank for the report.
With a simple armature with child I don't get error. You can send me the blend file ? I will try to reproduce on my side.

**Comment by xavier150** [comment]
Hello, you still have issues?
