### ISSUE TITLE
Does the addon really work with UE5?

### ISSUE THREAD

**Issue by vboudewijn** [xavier150/Blender-For-UnrealEngine-Addons#129]
Hi there,

I'm trying the add-on. In your Github it states it also works with UE5, I don't have any succes with that. In UE4 it works fine, but when I try to load it into UE5, the camera just imports in the scene center with no animation. I have python plugins enabled.

Could you explain how it can work in UE5?

**Comment by xavier150** [comment]
Hello, you still have issues?

**Comment by polidox2** [comment]
addon works perfect with UE5 and blender 3.0

**Comment by 3dcinetv** [comment]
is it working with Blender 3.2.2 and Unreal 5 (May 2022 update?)

**Comment by xavier150** [comment]
Hey @3dcinetv I not yet publish the last release.
You can try the last dev branch here: https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch

**Comment by xavier150** [comment]
If all good I will close this issue after the update release.
