### ISSUE TITLE
Not working if UE4 project is on a different Drive

### ISSUE THREAD

**Issue by VGuerreiro** [xavier150/Blender-For-UnrealEngine-Addons#133]
Hey there! 
First of all, thank you so much for this awesome tool! It's really useful!

I was trying to have it work in a manner such that clicking the 'export to UE4' button in the addon UI would automatically re-import the assets in the UE4. For this, I was providing the specific folder I intended for the assets to be imported into, in UE4 ( as an example: 'D:\UE4Projects\Test\Content\StaticMesh\') - I was inputting this path into the 'StaticMesh Export file path' field in the addon's UI.

At first, it didn't work (python error within Blender), I read the thrown error and found that it needed OS permissions (I'm on windows10). So I opened the blender project as Admin (this is inconvenient for a daily workflow, but I'm not sure much can be done in this regard (any suggestions would be awesome!). 
After this, the Export function went without any errors nor warnings, just worked (or so it looked like)!
When I opened the UE4 editor nothing was there, I opened the specified directory in Explorer, and nothing, no files to be seen.

I've found the files in the root directory, where my .blend file was. So, instead of following through to the path I've provided, it created a directory tree: D>UE4Projects>Test>Content>StaticMesh. It appears that instead of reading it as a path in Drive D:\ , the addon just created the folders in the same folder where the .blend file was.

I'm not sure if this is to be considered a bug specifically, but it's an issue for sure IMO.
If this doesn't work is there any way for the exported assets to be automatically updated/re-imported in UE4 whenever they're updated and exported in Blender using your addon?

**Comment by xavier150** [comment]
Hey @VGuerreiro Thanks!

In Nomenclature section you can chose how export the assets: 
![image](https://user-images.githubusercontent.com/7216958/140580712-f863bea3-50af-4eb0-911b-6c19cc73963e.png)
'//ExportedFbx' mean that the assets will be exported in the folder ExportedFbx side to blender file.
You can change this for 'D:\UE4Projects\Test\Content\StaticMesh' ^^

And to automatically import the assets, just run the code generated for export in Unreal Engine with the pythons plugins.
![image](https://user-images.githubusercontent.com/7216958/140581363-92a2c6ba-7fe7-43ef-a2ff-089887f19713.png)

**Comment by VGuerreiro** [comment]
Hey there! Thank you for the reply!
That's the process I used.  But it's not working because, as described above: 

"When I opened the UE4 editor nothing was there, I opened the specified directory in Explorer, and nothing, no files to be seen.
I've found the files in the root directory, where my .blend file was. So, instead of following through to the path I've provided, it created a directory tree: D>UE4Projects>Test>Content>StaticMesh. It appears that instead of reading it as a path in Drive D:\ , the addon just created the folders in the same folder where the .blend file was."

The Addon is seemingly not reading the string "D:\" correctly and instead of exporting the file in the desired folder, it's creating an entire directory in the same folder that the blend file is, not in the D:\ drive etc and for that to go without errors Blender needs to be launched in Admin mode.

**Comment by xavier150** [comment]
Oooh, that a bug, my code removed ":" in the path. I just fixed. You can try the last Dev Branch?
Last Dev Branch: [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch)

**Comment by VGuerreiro** [comment]
Oh! That's it I think! Awesome! I'll give that a try tomorrow and I'll let you know how it goes. 
Thanks a lot for replying! I'll update here ASAP
