### ISSUE TITLE
skeleton not exported

### ISSUE THREAD

**Issue by itmuckel** [xavier150/Blender-For-UnrealEngine-Addons#134]
I try to export a collection of meshes animated by one armature.
I get:

```
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "D:/Blender/station_interior/ExportedFbx/ImportAssetScript.py", line 489, in <module>
LogPython: Error:     print(ImportAllAssets())
LogPython: Error:   File "D:/Blender/station_interior/ExportedFbx/ImportAssetScript.py", line 444, in ImportAllAssets
LogPython: Error:     ImportAsset(asset)
LogPython: Error:   File "D:/Blender/station_interior/ExportedFbx/ImportAssetScript.py", line 430, in ImportAsset
LogPython: Error:     ImportTask()
LogPython: Error:   File "D:/Blender/station_interior/ExportedFbx/ImportAssetScript.py", line 353, in ImportTask
LogPython: Error:     skeleton = asset.get_editor_property('skeleton')
LogPython: Error: Exception: StaticMesh: Failed to find property 'skeleton' for attribute 'skeleton' on 'StaticMesh'
```
It's a DoorFrame, two Doors and one Armature. When I use the generated import script, I only get static meshes, but no skeletal mesh and no animations.

UE 4.27.1
Blender 2.93.4
Blender for Unreal Engine 0.3.0

![grafik](https://user-images.githubusercontent.com/18561536/139350223-ab4608f6-77a9-4447-9316-76827420427d.png)

I also created VertexGroups for each object with the same name as the respective bone, I named the non-moving bone "Root", also the plugin doesn't find errors.

What am I doing wrong?

**Comment by xavier150** [comment]
Hey @itmuckel! Thanks for the report, that maybe a bug. 
You can send me the file? I will try to found why that don't work.

**Comment by itmuckel** [comment]
Hey Xavier! Thank you for your help. I tried exporting it myself manually for days, but the individual doors are weirdly offset. I also restructured the armature a bit in blender (the bones now point up), but the skeleton still won't export correctly.

[station_interior.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/7489392/station_interior.zip)
All the other stuff in that file exports perfectly fine, but not the door in the separate collection.

**Comment by xavier150** [comment]
Hey @itmuckel 
It's because you didn't parent your asset correctly. 
You used the parent bone, but you need use the Vertex Groups for parent the vertex to bone. 

Do like this video and that should work ^^
https://user-images.githubusercontent.com/7216958/140648518-b49850b7-c204-47fc-84dd-d442e5f2f33f.mp4

I will add this to the potential errors.

More info 
https://docs.blender.org/manual/en/latest/sculpt_paint/weight_paint/usage.html
https://www.youtube.com/watch?v=dKZrzG5r13g

**Comment by itmuckel** [comment]
Uff, thank you so much! I thought parenting a whole object with a bone would automatically make it move with the bone. Which it did in blender and made it even more confusing. Also thanks for the extra resources, it exports now perfectly fine! 👍
