### ISSUE TITLE
Skeletal Animations Not Importing Correctly

### ISSUE THREAD

**Issue by KingKong19100** [xavier150/Blender-For-UnrealEngine-Addons#136]
Hey there! I am working on this animation and I am having many issues when it comes to exporting actual skeletal meshes. It seems as though the scaling and the exact positions are not being kept from Blender to Unreal Engine. I have selected the armature, checked "Export Recursive", unchecked "Move to Center", checked the Skeletal Mesh/Animations/Static Mesh/Collections/Import Asset Sequence filters under Export Filters, and I have exported the models. I copied the asset scripts and pasted it into Unreal, and when the skeletal meshes and the animations imported they did not have the exact positions they do in Blender. This is very important as the animation I am working on has a lot of compositing tricks rendered in Blender and it's important the two images line up. It works perfectly fine for Static Meshes. But for Skeletal Meshes with these animations, it does not work well. Is there something wrong? Is there any way you can help me?

Also, I am having another issue involving the models. The model in Blender has a separate Eye Mesh that is parented to the Eye Bone in the Armature, but these Eye Meshes with their Shape Keys are not exporting from Blender to Unreal correctly. Is there any way you can help me out with these issues?

Here are the versions for the programs I am using:

Blender 2.93.1
Unreal Engine 4.26.2
Blender-For-UnrealEngine 0.3.0

The Blend file was a bit too big so I emailed it to you. Please let me know, as I do have a deadline for this project! Kind regards.

**Comment by xavier150** [comment]
Hey @KingKong19100,
You can do this like that:
- Keep your skeleton at the center of the scene and use your rig for place the character.
- Offset your character in Blender and use the same offset un Unreal Engine.

![image](https://user-images.githubusercontent.com/7216958/140583841-7b7856e0-9865-4a44-affd-442e723daa0e.png)

**Comment by KingKong19100** [comment]
Hey there! So I already have scenes where the armatures are not centered, but they don’t have any keyframe animation. I use the root bones of my models to act as location movers, and this seemed to work fine previously. But it seems as though the armatures object locations are not staying the exact positions. I have helicopters in the scene which also seem to be not be moving correctly. Is there any ways this can be fixed?

I also have the issues of the eye meshes not moving correctly and exporting correctly. Any ideas?

**Comment by KingKong19100** [comment]
Hey there! So I already have scenes where the armatures are not centered, but they don’t have any keyframe animation. I use the root bones of my models to act as location movers, and this seemed to work fine previously. But it seems as though the armatures object locations are not staying the exact positions. I have helicopters in the scene which also seem to be not be moving correctly. Is there any ways this can be fixed?

I also have the issues of the eye meshes not moving correctly and exporting correctly. Any ideas?

**Comment by xavier150** [comment]
Hey @KingKong19100 
Try this:

- Place your all armatures objects to the center: no location, no rotation, scale at 1,1,1
- If you have animation on the transform (ColoredZone) right clic and clear
![image](https://user-images.githubusercontent.com/7216958/140650811-933c3fa7-797c-4a78-8790-d59b35488a6f.png)
- Don't use Contraints on the armatures objects
![image](https://user-images.githubusercontent.com/7216958/140650902-e73072a3-f5e6-4b7b-b980-4354f532284c.png)
- In the animation use only the bones in the rig not the rig location

**Comment by KingKong19100** [comment]
> Hey @KingKong19100, You can do this like that:
> 
> * Keep your skeleton at the center of the scene and use your rig for place the character.
> * Offset your character in Blender and use the same offset un Unreal Engine.
> 
> ![image](https://user-images.githubusercontent.com/7216958/140583841-7b7856e0-9865-4a44-affd-442e723daa0e.png)

Hey @xavier150, so when you say "Offset your character in Blender and _use the same offset in Unreal _Engine,__ is there a setting in the add-on that will allow for this? I can see that under "Object Advanced Properties" that there is an Additional Location Rotation and Global Scale option. Wouldn't this be able to help me offset the character in Blender for UE?

**Comment by xavier150** [comment]
No options for that, you need do that at hand with the position of your actor in the Unreal scene.

That why that better to use the bones to animate the position of your characters and not the armature position.

**Comment by KingKong19100** [comment]
> No options for that, you need do that at hand with the position of your actor in the Unreal scene.
> 
> That why that better to use the bones to animate the position of your characters and not the armature position.

Not even a worry, friend, I found a solution! This is pasted from my notes which I plan on turning into a video, so forgive the demeanor haha.

"I ran into another issue that was pretty hard to solve. ALWAYS remember to keep all of your models armatures at the zero location and the scale at 1 before you animate. Always apply Location, Rotation, and Scale. If you’re one of the unfortunate people like me who animated everything perfectly but then realized you moved your armature in object mode without applying the Loc/Rot/Scale, fortunately you’re not out of luck. I tried animating the Delta Transforms, I tried applying the Loc/Rot/Scale, nothing. So my solution was actually quite simple. Firstly, keep in mind the scale of your armature in object mode. Since I animated my rigs with a Root Bone to act as the main location point, what I would do is first enter pose mode and select the root bone, hit Cursor to Selected, and then go back into Object Mode. I’d zero out the location and scale for the armature in object mode, go back into pose mode and select my root bone, then I would hit Snap Selection to Cursor. Keeping in mind your scale, just hit S and scale it to the exact scale it was at before. Done. This was actually a huge time saver for me. Now you’ll notice that your scale is all fucked up now, but no worries. Before you start, duplicate the animation and collection to have that reference of where your Root Bone will be so you can keep snapping the cursor to that location. So again, what we’re basically doing is duplicating our model with it’s animation, zeroing out the location and rotation of the armature in object mode (this will be the correct one), enter pose mode with both armatures selected, then it’s simple as snapping your cursor to the origin of the original model, selecting the root of your new model, then just snapping your selection to the cursor then scale the root to what the original scale of the armature is! And just like that, you’ve solved the issue of not applying your Loc/Rot/Scale before animating!"
