### ISSUE TITLE
Cant install it

### ISSUE THREAD

**Issue by LucianoDaluz** [xavier150/Blender-For-UnrealEngine-Addons#139]
Does it have any trick to install it on Blender? Seems like it is not working. I mean I installed it and it does not appears on the addon list.

**Comment by LucianoDaluz** [comment]
By the way, using 2.93.6

**Comment by xavier150** [comment]
You installed from the releases?
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases

**Comment by LucianoDaluz** [comment]
> 
> 
> You installed from the releases? https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases

You just became my NEW HERO! Thank you sir!
![image](https://user-images.githubusercontent.com/94625454/142442596-be422a93-ffe5-4a0e-be10-7366d2b290a2.png)

**Comment by xavier150** [comment]
Yay :3
