### ISSUE TITLE
0.31 - Removes selected object from scene when exporting collections

### ISSUE THREAD

**Issue by TrillNeato** [xavier150/Blender-For-UnrealEngine-Addons#141]
With 0.31 I've noticed in several of my scenes the exporter removes the active object selection from the scene when I export.
![image](https://user-images.githubusercontent.com/7545197/143137565-49dd90ad-4cd2-485e-b833-7eb3e1242551.png)

It's frustrating because it also doesn't have a step in undo history so I have to reload my scene to get the object back.

**Comment by xavier150** [comment]
Hey @TrillNeato, ^^
I'm sorry for that that. I assigned a wrong value in the code. Thanks for the report!
You can try the dev branch? That should work now.
- Fixed: Remove the active object if an exported collection contain a single object.

**Comment by TrillNeato** [comment]
This has not been an issue for the week I've used this revision, thanks again 🥇
