### ISSUE TITLE
Transfer " Mapping" animation from blender to unreal

### ISSUE THREAD

**Issue by polidox2** [xavier150/Blender-For-UnrealEngine-Addons#143]
Hello,
so i have this eye animation,  
![image](https://user-images.githubusercontent.com/29620611/144755199-1af260f8-f78d-4065-85f2-510b17ea0063.png)
![image](https://user-images.githubusercontent.com/29620611/144755207-c69bc97a-c7e2-4474-a619-5479fb560d16.png)

it was animated using this:
![image](https://user-images.githubusercontent.com/29620611/144755218-8dadfb33-86bd-4090-9bc2-42421da2eb2d.png)

i was wondering how can transfer this animation to unreal using the plugin because currently it doesnt work.

**Comment by xavier150** [comment]
Hello @polidox2 
You can use Shape Keys for export animation curves and use the curves in Unreal Engine for control materials.
https://docs.unrealengine.com/4.27/en-US/AnimatingObjects/SkeletalMeshAnimation/Sequences/Curves/

**Comment by polidox2** [comment]
thanks!!
