### ISSUE TITLE
Shape Keys on Skeletal Mesh and Child Skeletal Mesh?

### ISSUE THREAD

**Issue by KingKong19100** [xavier150/Blender-For-UnrealEngine-Addons#144]
I have a character who uses Shape Key Animations on their mesh, and I was wondering how I would go about exporting the animation to Unreal?

I also have a character with a separate parented eye mesh, and this mesh also uses Shape Keys. It exports to Unreal but it does not maintain the Shape Key animations. How would I be able to preserve this? If only the first question can be solved, that should be fine, as I'd be able to just delete the body mesh and export to Unreal regardless.

**Comment by polidox2** [comment]
shapekey works perfectly with the plugin, make sure you have a driver.

**Comment by xavier150** [comment]
Hello @KingKong19100 You still have issue? 
The shapes keys are imported in the skeletal mesh and key animation with the anim files
