### ISSUE TITLE
Rotational Problem in Unreal

### ISSUE THREAD

**Issue by dosgoats** [xavier150/Blender-For-UnrealEngine-Addons#148]
Hi,

Thanks so much for this add on, it's really working well.

I had a hopefully minor issue where a tracked camera from Nuke is exported as an ABC and brought into Blender and then into Unreal.

In Unreal it appears to be working great but halfway through the animation, it flips around. It's still pointed in the same direction but all the Yaw values are now negative. This flip is not evident in Blender or Nuke. I've tried various formats of export from Nuke with the same issue in Unreal.

Is there anything in the Blender export that might fix this?

Thanks again,
Nick

**Comment by dosgoats** [comment]
Here are screen shots from Unreal showing the value change from frame to frame:

![Screenshot 2022-01-18 210150](https://user-images.githubusercontent.com/98004974/150067318-592a4137-04f5-42a5-8ff3-193770584ea6.jpg)
![Screenshot 2022-01-18 210123](https://user-images.githubusercontent.com/98004974/150067320-c665d4f3-b818-4299-bbb9-f38d06f3ac6a.jpg)

**Comment by xavier150** [comment]
Hello @dosgoats ^^
You can try Euler Filter:
- Select all animation euler curves in the Graph Editor
- Still in the graph editor Key -> Euler Discontinuity Filter

![image](https://user-images.githubusercontent.com/7216958/150279804-6bdd3d89-9811-4def-b559-37ad455fac2b.png)

**Comment by dosgoats** [comment]
Hi @xavier150 

I just gave that a try and it didn't seem to fix the issue, but I'm not too familiar with Blender to be 100% sure. Should any value change when selecting the Discontinuity Euler Filter? Or should I see a change in the graph? I'm still getting the minus value switching to a positive value, which causes 2 frames to be motion blurred. 

Since I was getting a little desperate I tried manually editing the JSON script but with the minus value added, the track breaks, since it starts reversing the rotation. I'm also having to use an FBX to see the keyframes and to correctly orient it to match the ABC, I've been adjusting it with the delta transform. Not sure if any of that helps you to see what my issue might be. 

Thanks so much!

**Comment by xavier150** [comment]
Yeah the curve should change, you can seen me the blend file with the camera? I will look about

**Comment by xavier150** [comment]
Hey @dosgoats 
Sorry for the delay. I test and found the issue! When I do export my addon will track the camera rotation and offset for export with Unreal Rotation. But this can do axis flipping.

I added a function for check and fix axis flipping during the export, that should work a lot better now.
![image](https://user-images.githubusercontent.com/7216958/150668617-7ea8d158-2e8e-4cac-aadf-d153dcc7ff71.png)

I updated the dev Branch: [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch)
Try and tell me if all work good for you.

**Comment by dosgoats** [comment]
Excellent! I will give it a try! Thank you so much.

**Comment by xavier150** [comment]
Tt works good now? You can close this issue if all work good ^^

**Comment by dosgoats** [comment]
I just tested a camera and it looks like it's fixed. Thank you again!
