### ISSUE TITLE
LOD settings not correctly imported

### ISSUE THREAD

**Issue by AlexelTech** [xavier150/Blender-For-UnrealEngine-Addons#15]
LOD meshes are imported as separate objects but not integrated in the mesh as LODs.
All settings looked correct (LOD1 mesh "is LOD" checked, and referenced in LOD0 setting), plus set as a child object of the main (LOD0) object. LOD import was activated in UE4... Maybe there is a step I missed ?
(UCX worked perfectly, though...)

**Comment by xavier150** [comment]
Hey AlexelTech !
Thanks for the report, currently lods only works with Static Mesh, and with 20Tab python integration. 
Can you send me the file, I will try to find the problem
