### ISSUE TITLE
 issue with Import to ue5 

### ISSUE THREAD

**Issue by jaqus** [xavier150/Blender-For-UnrealEngine-Addons#150]
hi 
I tried to export the camera to ue5 and after pasting in command 
Nothing loads and this shows up 
![image](https://user-images.githubusercontent.com/100779263/156372892-74251549-7ec0-4f59-a721-481f2223cd2d.png)

**Comment by kumaranjeya** [comment]
Yes. In the latest UE5 Preview 1 having similar issue as mentioned by @jaqus.
(By the way, in the car scene example-Youtube Video, are you using plugin for the car and the camera rig? Kindly inform. Much appreciated. Thank you.)

**Comment by curkan** [comment]
same problem

**Comment by xavier150** [comment]
Hello all,
Thank you for the report!
I published a new preview version for fix this issue.
v0.3.1 (Preview 2): https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v0.3.1_preview2

**Comment by xavier150** [comment]
> Yes. In the latest UE5 Preview 1 having similar issue as mentioned by @jaqus. (@xavier150, By the way, in the car scene example-Youtube Video, are you using plugin for the car and the camera rig? Kindly advise. Much appreciated. Thank you.)

I not used plugin in the video, that just a rig for animate cameras but that of course work without the rig.

**Comment by xavier150** [comment]
If all good I will close this issue after the update release.
