### ISSUE TITLE
Left panel missing

### ISSUE THREAD

**Issue by larinius** [xavier150/Blender-For-UnrealEngine-Addons#151]
Latest Blender 3.1
No panel below tools.

![image](https://user-images.githubusercontent.com/5310985/160203114-04b10238-e4bd-42b2-8930-f9f9f54948b3.png)

**Comment by xavier150** [comment]
Hello @larinius ,
I moved it panel on the right side panel ^^
![OtherSide](https://user-images.githubusercontent.com/7216958/160222589-b8e448d8-b74e-4e10-b427-c53e4639cfe2.jpg)
