### ISSUE TITLE
0.2.3c support for Blender 3.X(or optional 20tab integration for the recent builds)

### ISSUE THREAD

**Issue by Rythus711** [xavier150/Blender-For-UnrealEngine-Addons#152]
I found about the script during 2021 when searching for better workflow solutions between Blender and UE4, mostly based at QoL stuff like importing sockets for multiple and skeletal meshes, bypass the armature root bone issue, etc... unsure the stance of the team related of the use of the scripts for non-commercial and grey area-ish stuff like game modding, as i understand the common use for those scripts would be for own scratch-made game projects

The game i tend to work at model modding is based on UE4.18, unfortunately the only version that could communicate well was the 0.2.3c, which got the 20tab python integration, and currently the newer Blender-For-UE4 uses the native python plugins from Epic, and not so long Blender reached the 3.0 version, which unfortunately broke the support of that version on the importassetscript python code, which was a error about wanting inits instead of floats

Aside of the obvious, due Blender allows that as a portable software which is using versions like 2.9 for still working with that version, most people would originally start by downloading the most recent version and get headaches trying to solve the issues, and based on an user friendly guide i was working but progress went on hold due i went away from social networks for focusing on personal life and hardware issues, i want to explain it in a way that turns straightforward and easy for most Blender newcomers, and despite i could explain of using 2.9 and 0.2.3c, few could ignore by innocence and download Rev 0.3.0 and 3.1 instead, then receive an unecessary issue report that wasn't my fault originally

I know rewriting a whole old version just for begin supported with a new version of the source program that got different python structure would be very tedious, and just for a single user and a niche group of hobby creators wouldn't worth it either, but not sure if reintegrating the 20tab support as optional could be possible, seeing it would be enough already to work with old versions of UE4 that lacks the new python plugins which is my case, and i could even make use of both the new script versions and Blender 3.x QoLs like PBR Shader presets on viewport

Awaiting for a reply when possible, hope you're doing well this month also

**Comment by polidox2** [comment]
how about instead of letting the dev who is super busy doing a downgrade, you do an upgrade like everyone on earth ?

**Comment by Rythus711** [comment]
yeah, i clearly understand seeing Xavier got his real life to focus too, but my business isn't begin a programer, but a user of tools. i understand how to use pythons scripts, be it Blender or standalone, however, i lack knowledge at coding and programing in general, even if i took time to learn it(and i would focus on other areas that will benefit my job career instead), fixing a Python script isn't simply "modify a single string", as a fix would require editing from 2 to more lines resulting the error conflict, and try it until both the script is running, and the function works as indeed

and as i said on my "walls of text", i agree the effort for a single user like me and niche fanbase wouldn't worth it either, so rewriting 0.2.3c just for support Blender 3.0 is a tedious work, which is why i suggested the 20tab as a alternative, but i can also understand reimplementing 20tab can be painful as the first idea either, depending of Xavier answer, won't be mad either if i receive a no, i'll respect without issues, as begging isn't the solution for any area of research and programing, and i learned that by following forums since

**Comment by xavier150** [comment]
Hello @Rythus711 
Thank you for your interest in my addon. Unfortunately I will not update 0.2.3c and I will not redo 20tab integration.

I think the best would be to update Unreal Engine: You can switch to 4.27 or take the opportunity to use version 5 of Unreal Engine. You can also continue to use an old version of Blender if you can't switch engine or don't use the importassetscript python code

**Comment by Rythus711** [comment]
Hi Xavier, thanks for the reply(and sorry if i went at replying the user above), i clearly understand seeing coding in general is hard, so both the tasks would be very complex for a minimum effort, unfortunately i couldn't use 4.27 for what i work seeing the version by default is 4.18, despite preloads from 4.16 to 4.20 would be possible to a extent, it would generate other issues either as people would need to always take note of which version of UE4 the assets were made with a tool we tend to use for checking cooked assets, however i wouldn't have any issues of using and mentioning a old version of Blender for still working the script, i would need to take note on the guide, and it would be confusing for people at first needing old version of both, but is a minimum effort that i can open a exception, as i was originally a 2.49b user long time ago, but with time i went from 2.79 and the 2.92 as natural evolution.

thank you for taking a bit of you time for giving an answer, your addon indeed is very useful i have to agree, seeing most users from the niche fandom tried to dialogue it with other git repositories of UE4 tools asking for support of the game we work, and most turned successful, with that in mind at least i tried to enter in contact as a option, despite i did also understand fixing a python script in general isn't a easy task, and it would take a considerable time for getting satisfactory results, and it would work for some time until the newer Blender 3.x builds or plausible 4.x builds broke the support again

have a nice week, and wish the best for the development of the script
