### ISSUE TITLE
(feature request / question) Ability to toggle export for hidden objects

### ISSUE THREAD

**Issue by CGDJay** [xavier150/Blender-For-UnrealEngine-Addons#155]
is it possible to have the ability to make it not export hidden objects that are parented to the object you are attempting to export? This would help for making assets in which you need to make multiple variants of

**Comment by xavier150** [comment]
Hello @CGDJay 
This may help:
In Export type: select Not exported, 
![image](https://user-images.githubusercontent.com/7216958/172743664-cc1c0ae1-924a-49ff-8fbe-f82d683e8494.png)
That will not export the objects that are parented with this.
