### ISSUE TITLE
Error Message Pasting Script in UE5

### ISSUE THREAD

**Issue by dosgoats** [xavier150/Blender-For-UnrealEngine-Addons#157]
Hi I'm getting this error message. I updated to Rev 0.3.1 - Preview 2 but still no luck.

I am using Blender 2.93.
![blender_error_message](https://user-images.githubusercontent.com/98004974/181640952-0295e35e-0cc4-4f05-944c-01d6e4bd85b5.jpg)
3

Thanks!

**Comment by xavier150** [comment]
Hey @dosgoats Sorry for that, I fixed this error but I not yet publish the release.
You can try the last dev branch here: https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch

**Comment by dosgoats** [comment]
Thanks for responding. It looks like I'm having an issue where the init.py files are not being written?

**Comment by xavier150** [comment]
I not understand you get an error ?

**Comment by dosgoats** [comment]
I solved the issue about the init.py. It was user error on my part. I had accidently unchecked the additional files section in the export filter. Let me reinstall the newest version and try it again in unreal 5. Thank you!
