### ISSUE TITLE
Installation Not Working on 2.80 Without Error

### ISSUE THREAD

**Issue by filibis** [xavier150/Blender-For-UnrealEngine-Addons#16]
Hi @xavier150 ,
I tried to install the addon for 2.8 but it just doesn't install when I select zip file without any error. I made sure I downloaded the 2.8 version.

Blender version I used: 2.80 (sub 74), branch: master, commit date: 2019-06-19 18:29, hash: `rBd30f72dfd8ac`

Thanks.

**Comment by xavier150** [comment]
Hey filibis, Thanks for the report ! 
I made a mistake with folder name in zip file. The folder need be "blender-for-unrealengine" not "blender-for-unrealengine - 2.8" You rename or retry to download zip file https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v.0.2.3b
