### ISSUE TITLE
Missing paths

### ISSUE THREAD

**Issue by RyderMorgan** [xavier150/Blender-For-UnrealEngine-Addons#160]
In the presets options to Export and show Global Properties the only thing that shows is *missing paths*

![Screenshot 2022-08-12 175703](https://user-images.githubusercontent.com/111161573/184461438-470ec79f-9cb3-41e4-9514-5c0456c26276.png)

I've removed and installed the addon multiple times and this is still an issue.

**Comment by xavier150** [comment]
Hello!, it because you need create your own preset
![image](https://user-images.githubusercontent.com/7216958/210782354-c66e78e7-d2d2-4e1a-aace-0cdb670842fd.png)
![image](https://user-images.githubusercontent.com/7216958/210782440-843d8bf3-23db-46ac-a845-e347c3b9b22d.png)
