### ISSUE TITLE
Non Uniform Scale Sockets scaled wrong

### ISSUE THREAD

**Issue by PierrePS** [xavier150/Blender-For-UnrealEngine-Addons#162]
When export a mesh with sockets that are non uniformly scaled the XYZ Scale Order appears to be wrong. When Scaling Y the exported Socked is scaled in Z. May be due to the auto-90°-rotation at export. Or maybe I'm doing something wrong here. 

Kind regards
Pierre

**Comment by xavier150** [comment]
Hello @PierrePS 
Thanks for the report! I fixed this issue in the dev branch. 
- Fixed: StaticSocketsAdd90X option break non uniform scale sockets

You can try the last dev branch here: https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch
I will close this issue after the update release.
