### ISSUE TITLE
Exporting with actions takes a long time

### ISSUE THREAD

**Issue by Maker261** [xavier150/Blender-For-UnrealEngine-Addons#166]
As the title says, exporting a rig with animated actions takes quite some time depending on the amount of actions.

This one project took 2 minutes to export everything since it has 15 actions plus the rig and character mesh
![Screenshot_2](https://user-images.githubusercontent.com/46901949/200357832-ed61a82d-96dd-49de-9f09-3fa3dcd40e3c.png)

is it cause how its processing every animation the same way as the rig? (eg: scale fixing)

Really nice addon btw. It really saves quite some time fixing the scale of a rig. Not to mention that you can also keep the size of the character how you want to keep it in sync with other objects.

**Comment by xavier150** [comment]
Hello @Maker261! I'm sorry for the delay.
Unfortunately I don't really have a solution to correct this issue, it's from the FBX export.
You can maybe change the value Sampling rate and simplify animations but this will have an impact on the file sizes and animation quality.

You can also in render property check Simplify. If the model has a lot of geometry this can make the export faster.
![image](https://user-images.githubusercontent.com/7216958/210089562-2f9b830b-05e9-441b-b87b-5b5af53c3b85.png)

Also about scale if you can use the unit scale at 0.01 it the best for Unreal Engine and this avoid rescale durring export
![image](https://user-images.githubusercontent.com/7216958/210089799-edff6a1c-0973-447e-84b4-de3dc8eb34ed.png)


And thanks you!
