### ISSUE TITLE
Objects under objects with pivot

### ISSUE THREAD

**Issue by adamszalaiart** [xavier150/Blender-For-UnrealEngine-Addons#167]
Hey there!
I try to create some objects under objects with pivot, but only exports the item under the pivot (pivot is an empty)
https://drive.google.com/file/d/1X5Vb1kAdDmNVaZJZsXpOfwhH-yCoYbpg/view?usp=share_link

Do You have any idea, how should i setup the exporter to to able the export the whole hierarchy?

Thank You for your answer in advance!

**Comment by xavier150** [comment]
Hey @adamszalaiart ! 
I'm no sure to understand, if you need export the whole hierarchy under "Test_pivot" you can set Export recursive on "Test_pivot" 
![image](https://user-images.githubusercontent.com/7216958/210088898-f65090e6-5886-49b9-baa6-679198822abe.png)
So the addon will export the whole hierarchy using the Test_pivot origin as center

**Comment by adamszalaiart** [comment]
Sorry, i searched all in the exporter but i can't find Export recursive.
Btw i don't want to export the whole stuff with the Test_pivot origin as center
I want to export the whole hierarchy with the top parent object origin as center.

**Comment by xavier150** [comment]
Okay! So you need set Export recursive on "dfsdfsfs" that the top parent.
You can set here when you select the object:
![image](https://user-images.githubusercontent.com/7216958/210095014-8127f4f6-512a-4569-8b08-1fc1b2a41b5d.png)

**Comment by adamszalaiart** [comment]
I see the problem :)
I'm using  0.3.1, and You have  0.4.0
I downloaded the Blender-For-UnrealEngine-Addons-master.zip from this link:
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/archive/refs/heads/master.zip
Can You give me the download link of the version You are using please?

Thank You for your help already and the fast reply!

**Comment by xavier150** [comment]
Oh v0.4.0 is the dev branch but it works like in v0.3.1
![image](https://user-images.githubusercontent.com/7216958/210100290-64473a33-ec2a-4f8b-ac79-7ca688e09226.png)

You can download the files here -> https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation
And for the Dev Branch and version v0.4.0 follow this -> https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch

**Comment by adamszalaiart** [comment]
Thank You, now i found it and works!
Happy New Year! :)

**Comment by xavier150** [comment]
Happy new year! 😄 
I will close this issue now

**Comment by BaekIronFist** [comment]
Hello, following the topic but with different approach, is it possible to export assets parented as children of an empty? So far I'm not able to export hierarchies based on empty driven.

**Comment by xavier150** [comment]
@BaekIronFist That alredy work, that what I do
![image](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/assets/7216958/6c8f6ba0-1766-4f78-b4cb-27c08fb08150)

**Comment by adamszalaiart** [comment]
It's me again :)
While i try to export a hierarchy the code changes the name of the collision file. Please check the screenshot i attached here:
![export_vs_collision](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/assets/119440576/75264de7-c94f-4148-aec5-9402c231a64b)
only the root/dummy/empty is setup, everything else is created manually.
Can You update the exporter with a code that is not changing any naming during the export please?
Would be wonderful! :)
Thank You

**Comment by adamszalaiart** [comment]
Ahh i see, if the collision item is not under the SM content (in this case Cube), then code adds an SM into the item name.
Please ignore my last comment :) (i leave it here if somebody else also bumps into the thing)

**Comment by adamszalaiart** [comment]
Hey i'm here again with other issues :)

1-if i hit export button, exporter renumbers one of my collision:
![collision_numbers_vs_ueexport](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/assets/119440576/b7ca792c-fe46-4ccb-9d39-913e3265b0c2)

2-if fbx is read only, and i hit exporter button, exporter doing this:
![readonly_vs_exporter](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/assets/119440576/5aae1581-c747-4775-8652-f1cdf13fbfdb)

3-still would be awesome if leave collision undert the SM_ empty, then exporter shouldn't add an SM_ tag in the middle of the name of the collision item.

Important thing. i don't create those items with the exporter, because i already creating them with script, but still exporter shouldn't change any of the item names by itself.

Excepting that the exporter is awesome :)
