### ISSUE TITLE
Error upon trying to enable the addon

### ISSUE THREAD

**Issue by Diggydidggyholedwarf** [xavier150/Blender-For-UnrealEngine-Addons#170]
So as the title says I'm able to add the addon via the zip to my addons list however upon clicking the checkmark to enable the addon I get the following error and I'm not sure how to resolve it. Couldn't find anyone online with a similar issue so posting here hoping for some help.

Traceback (most recent call last):
  File "C:\Users\gamer\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2765, in draw
    addon_prefs = GetAddonPrefs()
  File "C:\Users\gamer\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-for-unrealengine\bfu_basics.py", line 31, in GetAddonPrefs
    return bpy.context.preferences.addons[__package__].preferences
KeyError: 'bpy_prop_collection[key]: key "blender-for-unrealengine" not found'

location: <unknown location>:-1

**Comment by ashishsinha24** [comment]
same problem

**Comment by xavier150** [comment]
Hello, you install the addon using the zip file ? https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation

**Comment by fizzi01** [comment]
> So as the title says I'm able to add the addon via the zip to my addons list however upon clicking the checkmark to enable the addon I get the following error and I'm not sure how to resolve it. Couldn't find anyone online with a similar issue so posting here hoping for some help.
> 
> Traceback (most recent call last): File "C:\Users\gamer\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2765, in draw addon_prefs = GetAddonPrefs() File "C:\Users\gamer\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-for-unrealengine\bfu_basics.py", line 31, in GetAddonPrefs return bpy.context.preferences.addons[**package**].preferences KeyError: 'bpy_prop_collection[key]: key "blender-for-unrealengine" not found'
> 
> location: :-1

Windows automatically blocks files coming from external sources. Right click and uncheck the last property.

**Comment by xavier150** [comment]
I close this issue, the addon 0.4.2 UI issue is fixed in Blender 2.9
