### ISSUE TITLE
this sucks

### ISSUE THREAD

**Issue by phil123456** [xavier150/Blender-For-UnrealEngine-Addons#172]
![image](https://user-images.githubusercontent.com/13568652/231835677-b0a95a99-3dd8-465a-8659-337fe4abad27.png)

**Comment by xavier150** [comment]
Read the wiki and tutos.
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki

You just need set the object you want to export as Export recursive

![image](https://user-images.githubusercontent.com/7216958/232847301-56ac817c-61b6-4dbd-af5a-e2d742b995aa.png)
