### ISSUE TITLE
Strange traceback error

### ISSUE THREAD

**Issue by TheScarletOne** [xavier150/Blender-For-UnrealEngine-Addons#173]
I'm having a strange issue when exporting this specific rig. I don't have the error with other models or even an earlier version of this file. The model is set up with a driver system to allow a weapon bone to tessellate transforms between a sheath bone and holding bone. This set up works on the other models but not this one, which also is the only one to have these errors.

> Python: Traceback (most recent call last):
>   File "C:\Users\Kyle\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-for-unrealengine\bfu_ui.py", line 2493, in execute
>     bfu_check_potential_error.UpdateUnrealPotentialError()
>   File "C:\Users\Kyle\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-for-unrealengine\bfu_check_potential_error.py", line 540, in UpdateUnrealPotentialError
>     CheckVertexGroupWeight()
>   File "C:\Users\Kyle\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-for-unrealengine\bfu_check_potential_error.py", line 486, in CheckVertexGroupWeight
>     VertexWithZeroWeight = GetVertexWithZeroWeight(
>   File "C:\Users\Kyle\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-for-unrealengine\bfu_check_potential_error.py", line 91, in GetVertexWithZeroWeight
>     if (Mesh.vertex_groups[GroupElem.group].name in
> IndexError: bpy_prop_collection[index]: index 54 out of range, size 5
> 
> location: <unknown location>:-1
> 
> 

I'm not 100% this error is even responsible for the transforms not exporting correctly on the weaponbone, but this is all also the only file with said error, so it's my biggest lead.

**Comment by xavier150** [comment]
Hello, maybe you closed the issue? If you still have the error maybe you can share me the file so I can try on my side
