### ISSUE TITLE
Like maya game exporter - move to origin

### ISSUE THREAD

**Issue by koloved** [xavier150/Blender-For-UnrealEngine-Addons#174]
https://www.youtube.com/watch?v=vdetqIh4n1A&t=176s

its a game changer feature for the addon 

The “Move To Origin” option in Maya Game Exporter is used to move objects or hierarchies to the scene origin (0, 0, 0) in the exported file.

is it possible in blender ?

**Comment by koloved** [comment]
sadly i am not a programmer ( 

`import bpy

# Save the current location of each object
positions = {}
for obj in bpy.context.scene.objects:
    positions[obj.name] = obj.location.copy()

# Move all selected objects to the origin
for obj in bpy.context.selected_objects:
    bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY')
    obj.location = (0, 0, 0)

# Export the scene

# Restore the original location of each object
for obj in bpy.context.scene.objects:
    obj.location = positions[obj.name]`

**Comment by koloved** [comment]
every collection can have kind of empty object which have RIGHT position of all objects in the collection

**Comment by koloved** [comment]
i ve found the similar script that allow it to do - https://github.com/mrtripie/Blender-Super-Batch-Export

**Comment by xavier150** [comment]
Hello @koloved 
I just see the post. This is already done by default, just have to try it.
![image](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/assets/7216958/247fe8e4-13a3-4a1c-b565-0cd01cf644b3)

**Comment by koloved** [comment]
@xavier150 yes, as i can see its only for objects not for collections

**Comment by xavier150** [comment]
Yes, collection for the moment is just for exporting several objects at same time as scene parts so no center to move. It better to use objects for move to center
