### ISSUE TITLE
Problems with rescale

### ISSUE THREAD

**Issue by Leopleordon** [xavier150/Blender-For-UnrealEngine-Addons#176]
Hello, the problem is in rescale, i don't like to work in 0.01 units in blender, when the camera moves away, the object disappears. By the way, I always have more than one object. And the textile also depends on it. For example, I have a modular building kit, already ready to be assembled in ue5, but here I am faced with rescaling problems when exporting. It turns out that all my assets must be set to the required size back to 0.01, also there will be problems in the texile. It's not nice, it's not about a couple of walls. Earlier, this problem did not exist; it seems to me 4 months ago, the addon exported everything correctly to me, so I did not think about measurements and worked as usual in meters. So far, I see a solution to the problem if you give me the opportunity to download the previous version. Thank you for your understanding. I will be glad if you suggest some other way to solve this problem.

**Comment by Klian326** [comment]
You can export using regular scale on blender, then set 0.01 as import scale in unreal btw

**Comment by Leopleordon** [comment]
> Вы можете экспортировать, используя обычный масштаб в блендере, а затем установить 0,01 в качестве масштаба импорта в нереальном, кстати.

how?)

**Comment by Leopleordon** [comment]
so far, I can only return the scale to 100 units in the ue itself. But in that case, I should forget about splines.
