### ISSUE TITLE
Custom property values in animation changing with manual rescale?

### ISSUE THREAD

**Issue by Ignorum** [xavier150/Blender-For-UnrealEngine-Addons#178]
Hello Mr. Raven!

Firstly, this add-on is a god-send. Absolutely fantastic, great work. Everything works splendidly, except for one issue.

I've encountered a bug regarding scaling, units and custom property values. Here's what's going on:

I have requirements for my project that need unit scale in blender to be set to 1, and I am trying to export animations that feature custom property keys.

When I export these animations using your plugin with scale in blender set to 1 and auto rescale enabled, the custom property key values get another two zeroes added to the start of them (1 becomes 0.01).

Everything else is fine, just the custom property keys get all messed up value-wise.

I'm not sure if it's a problem with what I'm doing, but this feels like a bug that I thought I'd make note of to help the next version be as good as it can be.

I'm using version 0.4.1 of the plugin on blender version 3.5.1.

Again, thank you for making this!

**Comment by xavier150** [comment]
Hello @Ignorum !
Sorry I just see you message, I will look about this issue durring the next week.

**Comment by xavier150** [comment]
Hello! I checking the old issues on github. I notice the answer was never send.

For Unreal Engine it recommended to use unit scale at 0.01, when it not at 0.01 my addon will re-scale the assets during export to fix the offset.

On your side if you need keep the unit scale at 1 you can disable the rescale in addon propertys.
![image](https://github.com/user-attachments/assets/19502376-e2a0-4e54-8b43-2b6e14217e3d)
