### ISSUE TITLE
Exported files overwrite all existing FBX in folder

### ISSUE THREAD

**Issue by jmobley0429** [xavier150/Blender-For-UnrealEngine-Addons#18]
Exporting multiple meshes into a folder with existing FBX files overwrites all FBX files in folder leaving only files exported in last batch. Not sure is this is a feature, I reviewed documentation and didnt see anything about this part of the addon.

**Comment by xavier150** [comment]
Hey jmobley0429 ! 
In addon preferences you need unchek Revert export path http://xavierloux.com/sharex/blender_2019-07-02_22-15-47.jpg
I will change to have false at default

**Comment by jmobley0429** [comment]
Okay thank you! Easy enough to fix I just exported my meshes from unreal.
Might have been messy if it was a bigger scene. Thanks anyway. It looks
like a great addon so far.

**Comment by xavier150** [comment]
Thanks !
