### ISSUE TITLE
Place in Active Level option breack materials

### ISSUE THREAD

**Issue by gentilearchitetto** [xavier150/Blender-For-UnrealEngine-Addons#180]
When I check the "Place in active level" option, the pushed assets are imported changing materials which in the meantime I had modified in Unreal, so I lost my work on materials setting.

The "Place in active level" option doesn't keep the material changes made in Unreal. So each time you push again from Blender to Unreal, it resets materials and you loose your work done in Unreal.

![immagine](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/assets/69249574/4f5f628e-4a1f-481e-b676-304c583a2687)

**Comment by xavier150** [comment]
Hello! this is not my addon ^^ 
Mine is [Blender For Unreal Engine](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#blender-for-unreal-engine) Try it :3

**Comment by gentilearchitetto** [comment]
Ops, pardon me, I wrote in the wrong repository 😅, I had to write in the Send to Unreal repository, but I’ll take your suggestion to try your addon.
