### ISSUE TITLE
Unable to copy sockets to unreal suddenly.

### ISSUE THREAD

**Issue by papa335677** [xavier150/Blender-For-UnrealEngine-Addons#183]
I've been using the copy skeletal mesh socket for a while but it's randomly stopped working, here's the error it shows.

Python: Traceback (most recent call last):
  File "C:\Users\trace\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-for-unrealengine\bfu_addon_parts\bfu_tool_ui_and_props.py", line 210, in execute
    bfu_basics.setWindowsClipboard(bfu_utils.GetImportSkeletalMeshSocketScriptCommand(obj))
  File "C:\Users\trace\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-for-unrealengine\bfu_utils.py", line 1363, in GetImportSkeletalMeshSocketScriptCommand
    sockets = GetSkeletalMeshSockets(obj)
  File "C:\Users\trace\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-for-unrealengine\bfu_utils.py", line 282, in GetSkeletalMeshSockets
    b = bfu_basics.getFirstDeformBoneParent(socket.parent.data.bones[socket.parent_bone])
AttributeError: 'Mesh' object has no attribute 'bones'

**Comment by RobertVater** [comment]
I also noticed that this seems to be related to merging objects in blender / deleting importet fbs skeleton. its quite random

**Comment by xavier150** [comment]
Hello @papa335677 @RobertVater !
I just see your messages.
I think this issue was fixed too in the last dev branch in version 0.4.2. [Dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/Download-And-Installation#download-and-installation-from-dev-branch)
Look about "Download and installation from dev Branch". After install restart Blender and try again.

If that don't work you can also send me the blender file so I will able to try on my side.

**Comment by papa335677** [comment]
> Hello @papa335677 @RobertVater ! I just see your messages. I think this issue was fixed too in the last dev branch in version 0.4.2. [Dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/Download-And-Installation#download-and-installation-from-dev-branch) Look about "Download and installation from dev Branch". After install restart Blender and try again.
> 
> If that don't work you can also send me the blender file so I will able to try on my side.

I can't seem to install the dev branch, do I need to uninstall my current version before installing it?
