### ISSUE TITLE
Camera Transform Data not importing

### ISSUE THREAD

**Issue by Manters** [xavier150/Blender-For-UnrealEngine-Addons#184]
Using v0.4.2 preview 2:
Blender version: 3.4-3.6
Unreal Version 5.3.2

I'm attempting to import a camera animation sequence to Unreal 5.3.2, but the camera transform data imports as blank. 
Other properties such as Current Aperture and Focal Length are being imported successfully.
![Untitled](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/assets/34168808/c9b1be8e-14c7-4e89-b166-058d9d10a082)

The output log in Unreal goes as follows:

Cmd: py "F:\Blender Stuff\DustCom\CurrentProj\CameraSequences\ExportedFbx\ImportSequencerScript.py"
LogPython: Warning this file already exists
LogSlate: Window 'Save Asset As' being destroyed
LogPython: Sequencer reference created <Object '/Game/Sequence/MySequence.MySequence' (0x0000085AF58F9600) Class 'LevelSequence'>
LogPython: ========================= Import started ! =========================
LogPython: Start camera import 1/1 :Camera
LogEditor: Attempting to add actor of class 'CineCameraActor' to level at 0.00,0.00,0.00
LogActorFactory: Actor Factory attempting to spawn Class /Script/CinematicCamera.CineCameraActor
LogActorFactory: Actor Factory spawned Class /Script/CinematicCamera.CineCameraActor as actor: CineCameraActor /Game/Main.Main:PersistentLevel.CineCameraActor_2
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "F:/Blender Stuff/DustCom/CurrentProj/CameraSequences/ExportedFbx/ImportSequencerScript.py", line 67, in <module>
LogPython: Error:     RunImportScriptWithJsonData()
LogPython: Error:   File "F:/Blender Stuff/DustCom/CurrentProj/CameraSequences/ExportedFbx/ImportSequencerScript.py", line 63, in RunImportScriptWithJsonData
LogPython: Error:     imported_module.run_sequencer_import(sequence_data, False)
LogPython: Error:   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-for-unrealengine\bfu_import_module\__init__.py", line 47, in run_sequencer_import
LogPython: Error:     return sequencer_import.CreateSequencer(sequence_data, show_finished_popup)
LogPython: Error:   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-for-unrealengine\bfu_import_module\sequencer_import.py", line 226, in CreateSequencer
LogPython: Error:     AddSequencerSectionTransformKeysByIniFile(transform_section, camera_tracks['Camera transform'])
LogPython: Error:   File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-for-unrealengine\bfu_import_module\sequencer_import.py", line 66, in AddSequencerSectionTransformKeysByIniFile
LogPython: Error:     if import_module_utils.is_unreal_version_greater_or_equal(5,0):
LogPython: Error: AttributeError: module 'bfu_import_module.import_module_utils' has no attribute 'is_unreal_version_greater_or_equal'

**Comment by xavier150** [comment]
Hello @Manters Sorry for the delay, can you try Preview3 ? It should be fixed now!

**Comment by Manters** [comment]
Hi @xavier150, thanks for your response.

I've tried installing Preview3 but I'm getting an error when I try to enable the addon in blender:
![Screenshot_2](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/assets/34168808/be00b984-30fb-43e5-83ee-f6bab84547c3)

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Ciarán\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-for-unrealengine\__init__.py", line 36, in <module>
    from . import bbpl
  File "C:\Users\Ciarán\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-for-unrealengine\bbpl\__init__.py", line 31, in <module>
    from . import blender_rig
  File "C:\Users\Ciarán\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-for-unrealengine\bbpl\blender_rig\__init__.py", line 27, in <module>
    from . import rig_utils
  File "C:\Users\Ciarán\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-for-unrealengine\bbpl\blender_rig\rig_utils.py", line 138, in <module>
    def add_bone_to_collection(arm, bone_name, collection_name) -> bpy.types.BoneCollection:
AttributeError: 'module' object has no attribute 'BoneCollection'

This error prevents me from being able to install the addon so I'm currently unable to verify if the camera transform now imports successfully. I've also tried installing the addon on a relatively untouched separate machine and in versions 3.4 -3.6 and it prompted the same error.

**Comment by xavier150** [comment]
Oh sorry for that, it because bpy.types.BoneCollection was added after Blender 3.6 I will fix that and push in Dev Branch. Please wait.

**Comment by xavier150** [comment]
I back, I fixed please try the last dev branch -> https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/Download-And-Installation-From-Dev-Branch

**Comment by Manters** [comment]
Just tested it now, installed correctly and appears to be exporting the camera transform data the camera correctly now. Many thanks for your efforts.

**Comment by xavier150** [comment]
A pleasure!
