### ISSUE TITLE
Nomenclature in the Preferences

### ISSUE THREAD

**Issue by michelchafouin** [xavier150/Blender-For-UnrealEngine-Addons#19]
This a more of a suggestion than a bug, but I would recommend to move the Nomenclature to the add-on preferences. It would be much easier to keep prefixes and export folder consistent across different blend files.

**Comment by xavier150** [comment]
Hey michelchafouin,
This is what was planned at the beginning but this is a problem if you work on several projects at the same time. So it's better to have a nomenclature saved directly with the file.
But it maybe possible to have an additional preferences nomenclature and an option for select preferences nomenclature  or scene nomenclature

**Comment by michelchafouin** [comment]
Creating nomenclature presets in the add-on preferences that you can then select in the Export tab would be good in-between.
