### ISSUE TITLE
Exporting Auto Rig Pro rig. Twist bones seems to be an issue.

### ISSUE THREAD

**Issue by Xiarno** [xavier150/Blender-For-UnrealEngine-Addons#192]
I'm not 100% certain that this is the issue I'm having, but when exporting a rig, the twist bone added by ARP seems to be making it behave pretty weirdly in Unreal Engine.

The default ARP exporter has an option to disable the Export of Twist bones. Is it possible to add it please? Thanks!
![14931_blender_KTTb72q29H](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/assets/24660485/1b330d76-c0cd-4661-b8d0-718357ef3d8a)

**Comment by xavier150** [comment]
Hello! 
Sorry I no longer use auto rig myself and I don't found info about ARP API, to control that. I will remove it in the future.
