### ISSUE TITLE
Animations are not exported to Sub Folder

### ISSUE THREAD

**Issue by ZeroNRG05** [xavier150/Blender-For-UnrealEngine-Addons#199]
When exporting to Unreal, skeletal animations are placed in the skeletal mesh folder, not the Anim sub folder.

Changing the path of the Anim sub folder doesn't seem to do anything.

**Comment by xavier150** [comment]
Hello @ZeroNRG05 
You can set the animation folder here:
![image](https://github.com/user-attachments/assets/980758b8-e53c-4c85-856a-c10153379130)

It seam to work in the last versions. What version are you using ?
![image](https://github.com/user-attachments/assets/624cc747-5863-47f1-8ddd-b8790c80e1fa)

**Comment by ZeroNRG05** [comment]
Sorry, I meant the **export folder**, on the disk, not the **import folder**, in unreal engine.

I usually import animations into unreal, manually, from the export folder. Previously, the .FBX animations were exported to a separate folder from the skeletal mesh, which made this easier.

**Comment by xavier150** [comment]
Ooh! you are right, I just fixed it and push the change in the dev branch. 
That will be for the next update but you can try the dev branch now here -> https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/Download-And-Installation-From-Dev-Branch

Thanks for the report!

**Comment by ZeroNRG05** [comment]
Works now, thanks!
