### ISSUE TITLE
Error: cannot import name "FrameRate"

### ISSUE THREAD

**Issue by Draise14** [xavier150/Blender-For-UnrealEngine-Addons#2]
I have exported and imported static meshes, but now I have difficulty doing the camera sequence export/import. In UE4, I have the Python console working and all is well - but I get an error when trying to run the camera sequencer import python script. 

I have two cameras bound to 3 markers. A cut back and forth to test. 

UE 4.19
Python 3.7 (embedded)

![ue4editor_2018-09-26_11-47-58](https://user-images.githubusercontent.com/35357409/46095394-08a8f580-c182-11e8-87f2-74fe7f3f96b5.png)

**Comment by Draise14** [comment]
I tried changing the loading state of the Python Console to "Predefault" but still haven't got the fix. 

![atom_2018-09-26_12-13-15](https://user-images.githubusercontent.com/35357409/46096797-be297800-c185-11e8-85eb-5ab39cbe84c8.png)

**Comment by xavier150** [comment]
Hello, I did not test with Unreal 4.19 and I get the same error as you
I will try to correct this when I come back tonight

**Comment by Draise14** [comment]
Ah ok, so manually set the FPS, ok, sounds like a reasonable workaround. I'll change the script. Thanks!

**Comment by xavier150** [comment]
It corrected, you can now choose Unreal version for script generation ^^ 
![Unreal version](http://xavierloux.com/sharex/blender_2018-09-27_23-52-03.png)
