### ISSUE TITLE
Rotation is applied during export

### ISSUE THREAD

**Issue by michelchafouin** [xavier150/Blender-For-UnrealEngine-Addons#20]
If the object you want to export has a rotation that is not 0, it will be applied during the import.
Would it be possible to have an option to preserve the rotation during export?
In Blender: RotationZ= 161
![blender_bCMyISSoLZ](https://user-images.githubusercontent.com/25534823/60801910-caca0a80-a1b2-11e9-8421-99168ed37e73.png)
In Unreal: RotationZ= 0
![UE4Editor_4OjEeMwtcQ](https://user-images.githubusercontent.com/25534823/60801917-cd2c6480-a1b2-11e9-852e-6ce243aab6b9.png)

This would be helpful to export entire scenes.

**Comment by xavier150** [comment]
Hey michelchafouin,
I plan to add options in avanced scene to select the coordinates to use like origin or rotation, I just added for rotation
https://trello.com/c/P2hjPAdZ/38-blender-for-unreal-engine-addon-24

**Comment by xavier150** [comment]
I do this in Rev 0.2.4 https://youtu.be/rbW5NcyNoK0
