### ISSUE TITLE
Freezes on exporting when there are many objects in the scene

### ISSUE THREAD

**Issue by sacrish** [xavier150/Blender-For-UnrealEngine-Addons#204]
I have a Blender file for my game character with a fair lot of WIP parts and backup objects placed in various hidden collections. And I have objects that are ready for export in a separate active collection. 

When I click export, Blender freezes and eventually crashes after a few minutes. I've tried checking the "Only Selected" option in export filter, and setting the modular export mode to "Specific Parts" and specifying objects I want to export, but those didn't help. 

So far the only way I got it to work is to delete all the unwanted objects from the file. And then I could export the character in a few seconds.

So I assume the "Only Selected" option doesn't really exclude hidden objects from the recursive search? Maybe it would be better to have an option to exclude or only include specific collections?

Edit: Checking the export collection under "Scene" mode doesn't help either. I still have to delete all other objects for it to not freeze.

**Comment by xavier150** [comment]
Hey @sacrish 
Yes this look like a bug, and if you use "Only Selected" it should not take in consideration other objects.
Please can you send me a copy of the Blend file? I will try on my side.

**Comment by sacrish** [comment]
The character is for an unpublished game so I'm afraid I can't share the file yet. I apologize for this. 

But I think I've pinpointed the problem! I've been testing by deleting things one by one from the file and try exporting. There's a Grease Pencil object (to do some outline effects for look dev) in a hidden collection. And when this Grease Pencil exists, the time spent on export gets extremely long (up to several minutes) if there are many other objects in the file. And if there are too many of them, the program freezes.

And once I delete the Grease Pencil, the export becomes a lot faster (10+ seconds), without the need to delete anything else.

I've uploaded a simple test file that contains the problematic Grease Pencil object and several dozen hidden cubes. You can check how it drastically slows down export:
[ue_export_stress_test.zip](https://github.com/user-attachments/files/18053140/ue_export_stress_test.zip)

**Comment by xavier150** [comment]
Hey @sacrish I has able to test, sadly I can't fix this issues. 
When Blender update the scene the Grease Pencil seam to take many time to update. 
The addon ignore the Grease Pencil during export but it need update the scene several times because it will duplicate the assets for export and so the scene update also update the Grease Pencil.

The scene get very slow too if you try to move Stroke with G or change current frame.

**Comment by sacrish** [comment]
Then I assume it's a Blender limitation (or bug? depending on whether or not Grease Pencil is intended to update even when it's hidden).

Fortunately the GP in my file was only for some early stage look dev so I don't need it anymore. And now the plugin works perfectly. Thanks for your effort btw. Your plugin has saved me a lot of time and braincells🫡

**Comment by xavier150** [comment]
I don't know at all to be honest. Maybe if it happened again you can use the "exclude option" on the collections. Look like it fully unload the objects, not just a hide.

![image](https://github.com/user-attachments/assets/41f32581-e94a-431a-aeb6-af87c863e5e7)

I'm harry to hear! ^^
