### ISSUE TITLE
Preset export paths are wrong in Linux

### ISSUE THREAD

**Issue by Clockwork-Muse** [xavier150/Blender-For-UnrealEngine-Addons#21]
By default, Linux uses a forward slash (`/`) to separate paths.  Using a back slash (`\`) causes blender to generate multiple directories with varying names, instead of a hierarchical structure as expected.
Also, for some reason this means that UE4 can't read any files or subdirectories, but I have no idea why.

In `__init__.py`, the path settings need to concatenate the directory names, not use a static string, to deal with this.

**Comment by xavier150** [comment]
Hey Clockwork-Muse,
You right, I have changed for os.path.join(...), I will publish a fix for Rev 0.2.3c, But before can you tell me if it works? I don't have machine with linux. [blender-for-unrealengine - 2.8.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/3378409/blender-for-unrealengine.-.2.8.zip)


About ue4 you talking about the import script?

**Comment by Clockwork-Muse** [comment]
Yes, this seems to have done it, thank you.

>  I don't have machine with linux. 

WSL or a Linux VM running in HyperV would also work (assuming you're on a version of Windows that can use them)

> About ue4 you talking about the import script?

No - just trying to import the files normally.  I'm assuming this is something strange in Unreal's file-picker
