### ISSUE TITLE
Collections visibility changes when exporting 

### ISSUE THREAD

**Issue by elomeno** [xavier150/Blender-For-UnrealEngine-Addons#22]
when I click export for UnrealEngine 4 and I have only one collection visible when it's finished the visibility changes to another collection

**Comment by xavier150** [comment]
Hey elomeno,
Thanks for the report, can you send me the file ? I will try to identify the problem

**Comment by elomeno** [comment]
the file is huge I will see if I can reproduce the problem in a new blend file. Thanks for reaching out!

**Comment by xavier150** [comment]
Ok, do not hesitate, no problem :)

**Comment by xavier150** [comment]
Since this has been corrected I think, do not hesitate to reopen if it does not work well
