### ISSUE TITLE
Export Custom Properties?

### ISSUE THREAD

**Issue by Jeff0029** [xavier150/Blender-For-UnrealEngine-Addons#23]
Would it be possible to export custom properties has an option?

![image](https://user-images.githubusercontent.com/6496893/61680275-fed71c80-acd6-11e9-8c6f-1db9f3ae56a1.png)

![image](https://user-images.githubusercontent.com/6496893/61680299-0f879280-acd7-11e9-80b3-64017d18bc23.png)

**Comment by xavier150** [comment]
Hey Jeff, 
You need export custom properties for what use ? In Unreal they are not used

**Comment by Jeff0029** [comment]
Hello Xavier,

They are accessible values as shown here.
![image](https://user-images.githubusercontent.com/6496893/61723072-6e7df380-ad39-11e9-96c2-be862ae6672a.png)

There are other ways I could send metadata down the pipeline, but this one felt simple for my 3D modelers.

Thank you,

Jeff

**Comment by xavier150** [comment]
Oh I see, I will add a option for use custom properties in addon preference with the next version soon

**Comment by Jeff0029** [comment]
Upon close inspection, the custom properties of the child nodes gets all grouped when I import.  I think I'll make a custom JSON file to keep the node hierarchy.  Sorry for the trouble!
