### ISSUE TITLE
Forward/Up Axes not working? Models laying on their side

### ISSUE THREAD

**Issue by RobertMtx** [xavier150/Blender-For-UnrealEngine-Addons#29]
Are the forward and up axes overrides functional? I seem to get the same import result regardless of what settings I use for the export axes. I have all of the Unreal options that influence this (Convert Scene) turned off .

Also, for some reason (maybe the same reason), all models I export using this add-on come in with Y=up (Z is actually up in both Blender and Unreal - objects just need rotated 90 degrees so that -Y is +X). This causes everything to be laying on its side.

I'm not sure if this will help, but it looks like using -X=forward and +Z=up for Blender's normal FBX export works perfectly for importing with all scene conversion turned off. All objects come in, on their feet, facing the +X axis. Not sure why -X works here (seems like it would be +X), but it appears to be the only setup that does without having Unreal fix it after.

**Comment by RobertMtx** [comment]
After playing around with writing my own exporter, I think I understand why. The forward and up axis variables of the exporter are strangely incorporated using the orientation_helper object. I'm still having trouble getting it to work.

**Comment by xavier150** [comment]
Hey RobertMtx !
Sorry for the delay exportAxisForward and exportAxisUp have been were disabled in the last version, but they will be reimplemented in the next.

I try again but I don't know why the value axis_forward and axis_up seems don't work with FBX Exporter :/ http://xavierloux.com/sharex/UE4Editor_2019-09-07_00-31-32.jpg

But I added a option for add additional rotation to the mesh in Avanced object properties panel, this can bay be help you for set object orientation with export !

(This is a non definitive version)
[blender-for-unrealengine - 2.8.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/3585954/blender-for-unrealengine.-.2.8.zip)
