### ISSUE TITLE
Correcting english for Import and Export guides.

### ISSUE THREAD

**Issue by abhisarshukla** [xavier150/Blender-For-UnrealEngine-Addons#31]
#### This plugin is great but  the Import and Export guides give a little bit of trouble. If you say so i can correct the english of  those guides and send you a pull request.

**Comment by xavier150** [comment]
Oh yes I have a very bad English, with pleasure, Thanks !

**Comment by abhisarshukla** [comment]
Almost completed correcting the export from blender guide. There is section about "Aramature and Skeleton Tree", in that there is word "egal", i think its "illegal".
Please correct me if I am wrong. @xavier150

**Comment by xavier150** [comment]
You speak about "You can set the name what the amature should use once exported in Addon Preferences. If egal "Armature" Ue4 will remove the root bone but the animation will be 100 times smaller." ?

I want say if the name used is named as "Armature" Ue4 will remove the root bone

**Comment by abhisarshukla** [comment]
Yeah I get it now.

**Comment by xavier150** [comment]
I merged, thank you very much !

**Comment by abhisarshukla** [comment]
Thanks for merging.
