### ISSUE TITLE
Can't activate plugin in corporate environment with proxies.

### ISSUE THREAD

**Issue by florsignol** [xavier150/Blender-For-UnrealEngine-Addons#33]
I'm trying to use the plugin, but can't even activate as it seems to want to contact github.com. Is there a way to use the plugin in an environment with no internet connection or limited by proxies?

**Comment by xavier150** [comment]
Hello florsignol,
Thanks for the report! I just fixit: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v.0.2.4b
The plugin try to contact github.com for see updates but get a error with no internet connection
