### ISSUE TITLE
Sockets rotation offset by 90 degrees

### ISSUE THREAD

**Issue by smeben** [xavier150/Blender-For-UnrealEngine-Addons#35]
Sockets currently need to be rotated 90 degrees on X before export

**Comment by xavier150** [comment]
Hello smeben,
That true on static mesh the socket are auto imported by unreal with -90 on X 
I will add a option for correct this

**Comment by xavier150** [comment]
Hello, I corrected and just updated https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v.0.2.5
