### ISSUE TITLE
Setting Object Properties On Multiple Objects at same time

### ISSUE THREAD

**Issue by MrPositivity** [xavier150/Blender-For-UnrealEngine-Addons#37]
Hello, I would like to know if there is any chance to implement possibility for multi-object editing?
Here is a problem I have 120 kit pices and now I need to go and set each Of them "Export recursive" to be able to export them.
Maybe there is something like that already but I was not able to find away.

**Comment by xavier150** [comment]
Hello MrPositivity, 
you should use python. selected the desired objects and run this script:

```
import bpy

for obj in bpy.context.selected_objects:
    obj.ExportEnum = 'export_recursive'
```
