### ISSUE TITLE
Camera sequencer can't import to Unreal

### ISSUE THREAD

**Issue by saikafu** [xavier150/Blender-For-UnrealEngine-Addons#38]
Hi Xavier150 
I have an issue while I import camera animation into unrreal engine, I've follow the tutorial with your video, but I still get this issue in unreal python console :

LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 1, in <module>
LogPython: Error: NameError: name 'unreal_engine' is not defined

anything I did wrong?

**Comment by xavier150** [comment]
Hello saikafu, 
Sorry I just see your comment.

You using generated scripts for 20tab python integration with vania python integration.
Doc: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/blob/master/Tuto/How%20import%20assets%20from%20Blender%20to%20Unreal.md

- If you want use 20tab integration you need install UnrealEnginePython plugin https://github.com/20tab/UnrealEnginePython
- If you want use vania integration you need set Use20TabScript on False in Blender addon preferences.

https://raw.githubusercontent.com/xavier150/Blender-For-UnrealEngine-Addons/master/Tuto/ImportAssetDocVaniaPython.jpg

https://github.com/xavier150/Blender-For-UnrealEngine-Addons/raw/master/Tuto/ImportAssetDocVaniaPythonUseCmd.jpg
