### ISSUE TITLE
Any chance a version of this might ever be released for Unity?

### ISSUE THREAD

**Issue by MostHated** [xavier150/Blender-For-UnrealEngine-Addons#39]
Hey there,
    You have done some amazing work here. even though I don't even use Unreal, I can appreciate how useful this would be. I know that it is no small feat, but was there perhaps any plans to one day create a version of this for Unity? If not, do you happen to know if there is a similar add-on that might be out there? I would certainly love to have something like this for it! I know this question really has nothing to do with your add-on in terms of a typical issue submission, so please, by all means feel free to close it if the question is simply not supposed to be here.

Thanks,
-MH

**Comment by xavier150** [comment]
Hey MostHated,
Thanks ! ^^ For the moment this is not planned but the Addon is already usable for Unity !
In Blender you can set export folder for export mesh directly In unity. Like that unity will detect them automatically

[http://xavierloux.com/sharex/12112019unityexportexemple.jpg](url)
