### ISSUE TITLE
Socket on exported skeletal mesh doesn't show up in unreal

### ISSUE THREAD

**Issue by idkw** [xavier150/Blender-For-UnrealEngine-Addons#4]
Hello,

Thanks for this plugin.
It really helps a lot when exporting stuff from Blender. It helps me avoid a lot of pitfalls of the FBX format.

I have however an issue with sockets, here is my blender file : 
[Rover1.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/2516226/Rover1.zip)

Blender: 2.79b
Plugin: 0.2.0
Unreal: 4.20.2

I have converted an empty object into a socket now called "SOCKET_weapon_1" parented to the RoverBody.
Then I export the Rover2 Amarture as recursive (for skeletal mesh) to FBX with the plugin.
However when I import the FBX into unreal engine, the socket doesn't show up in the created skeleton asset.
Am I doing something wrong or is it actually a bug ?

PS: j'ai cru voir que tu étais français dans les release notes, on peut parler sur discord si tu veux: valou#2737

Thanks !

**Comment by xavier150** [comment]
Hello Idkw,
Unfortunately Ue4 does not support Socket import with skeletal mesh :/ You need add it manualy unreal 
For the next version of the addons (0.2.2) I plan to add socket import with the import script

Oui je suis français ^^ je t'es envoyer une demande d'ajout
