### ISSUE TITLE
Driver controlled ShapeKeys are not exported in animations

### ISSUE THREAD

**Issue by Ikeiwa** [xavier150/Blender-For-UnrealEngine-Addons#40]
Hi !
I have a problem with the addon right now, (which is amazing btw) where animation that have animated custom properties that controls ShapeKeys are not exported, like, If I export using the default fbx exporter the shapekey tracks are present in UE4, but not when I export using the addon.
Is there something I'm missing or is it just unsupported right now ?
Also I suppose that's important to mention but I'm using linking and proxies, I have a main blend with the mesh and armature, and a blend for each animation (we use that for team work) with the main blend linked inside.

Btw I can send a test blend that has that problem if you want to test it yourself.

**Comment by xavier150** [comment]
Hi !
Sorry for the delay I just see your comment. 
This is a problem with proxies, to export animated ShapeKeys curves with actions you should export the mesh with the armature but if you export the proxies it export only the armature.
You should set proxy as parent of you collection with the mesh and export the proxy.
https://raw.githubusercontent.com/xavier150/Blender-For-UnrealEngine-Addons/master/Tuto/ExportAssetDocActionWithProxy.jpg
I just updated the doc.

**Comment by Ikeiwa** [comment]
Thank you ! It works perfectly. There is just on weird thing.
UE4 is giving warnings saying that extra bones are present in the animation and not in the skeletal mesh for some reason. The animation still works perfectly so it's not a problem but that's still weird.

**Comment by xavier150** [comment]
Nice :3 And yeah me too, it something I need correct in next version.
