### ISSUE TITLE
Workspace Filter 

### ISSUE THREAD

**Issue by Blenux** [xavier150/Blender-For-UnrealEngine-Addons#41]
Hi I just notice with the addon, if one wants to filter their add-on's list, enabling it disables access to this add-on completely, might be something to look into if possible.

![Annotation 2019-12-27 142104](https://user-images.githubusercontent.com/25260650/71500589-ba6d2f80-28b9-11ea-86f1-53e1b584003e.png)
![Annotation 2019-12-27 150558](https://user-images.githubusercontent.com/25260650/71500750-6adb3380-28ba-11ea-9669-e8109ab7d830.png)

**Comment by xavier150** [comment]
Hello!
Oh true! I will look about it in January for correct this
