### ISSUE TITLE
Animations are frozen in Unreal

### ISSUE THREAD

**Issue by borchy** [xavier150/Blender-For-UnrealEngine-Addons#43]
Hello! I tried installing and using the add-on for exporting a rigged model with animations to Unreal, but something's wrong. It would take way too long for me to describe all of my steps, and all of the properties, so I just shot a video demonstrating the issue: https://youtu.be/5J-37z7IPwo

**Comment by xavier150** [comment]
Hello @borchy Thanks for the report!
Can you send me the model ? I will try to reproduce to correct it

**Comment by xavier150** [comment]
This has been corrected I think, do not hesitate to reopen if it does not work good
