### ISSUE TITLE
Wrong center/origin

### ISSUE THREAD

**Issue by andgeno** [xavier150/Blender-For-UnrealEngine-Addons#45]
Hi, I'm having issues with exporting meshes with their correct center and origin point.

The docs state:

> The center of the scene of the Fbx file will be equal to the origin point location of the object in blender. The position of the object in the Blender scene does not matter.

But I find that this is not working this way. The origin shown inside Blender (orange dot) can be placed anywhere. All that matters is where I have placed the mesh in relation to world origin. This makes building a library a bit harder than it should be since I have to throw everything on world origin and toggle the visibility of my collections/objects.

**Comment by andgeno** [comment]
I noticed that the `Advanced object properties panel` is empty all the time. This might be connected to wrong center/origin problem I have ...

I watched the [video ](https://www.youtube.com/watch?v=rbW5NcyNoK0&feature=youtu.be)you provided about changing transforms and this panel is always empty for me no matter what I do.

**Comment by andgeno** [comment]
Alright, the advanced panel is only populated if an object's `Export type` is set to `Export recursive`. Otherwise it stays empty.

I was now able to try out the export transform feature `Move to center`. It does not matter whether it's enabled or disabled. I moved my mesh a bit along the X axis away from world origin. In both export tries the mesh contains the same offset.

Here's a screenshot to get a better idea of the scene:

![image](https://user-images.githubusercontent.com/2432608/74805639-fb932600-52e3-11ea-9058-25e53b780859.png)

**Comment by andgeno** [comment]
Yay, I found the issue. Another surprise next to having to change the object's `Export type`. The `Advanced object properties panel` is only respected if `Static Mesh(s)` is ticked in the `Export` panel. It does not suffice to select `Collection(s)` although the meshes were exported - just wrong/without the advanced export options.

I think both "surprises" should be added to the docs to avoid future confusion. 😀

**Comment by xavier150** [comment]
Hello Andgeno!
Hum I'm not sure I understood everything. The majority of the properties displayed in the panels will be the properties of the active object (The last select) you need set `Export recursive` on all the objects you want to export else it will never be exported. 

In export panel you need tick `Static Mesh(s)` only if you want export the Static Mesh with `Export recursive` from your scene. This will overwrite the old exported .FBX file and so apply the new Advanced object properties.

I added a note with the video about Advanced object properties

**Comment by andgeno** [comment]
I organized my scene like this:

![image](https://user-images.githubusercontent.com/2432608/74867242-99263e00-5354-11ea-9026-41520a7516ab.png)

Since every object is placed in its own collection I was able to export all the objects with export type set to `auto`. The `Static Mesh(s)` checkbox was **unticked**. Everything worked except that the FBX's origin was always set to world origin.

I think it would be a better user experience if the advanced panel would show a text that these settings will only be available when the object's export type is set to `recursive`. It should probably also say that the `Move to center` option will only work when you have `Static Mesh(s)` selected for export. I don't really understand why this works this way since it exporting a collection is the same to me as exporting the meshes. Could you please explain why there is a differentiation between the collection and static mesh export?

**Comment by xavier150** [comment]
If your export your mesh like a collection that's why the object is placed in the center. The origin of a collection is the center of the world. Example https://i.imgur.com/4iBL6Vx.jpg And the all properties that you put on your object will be ignored because it is not the object that you export but its collection which includes it. 

Here you just have to set 'Export recursive' on your objects and untick Collection(s) in export panel.

**Comment by andgeno** [comment]
Oh, this was helpful. Thanks!
