### ISSUE TITLE
Makehuman Export Animation issue

### ISSUE THREAD

**Issue by aknarts** [xavier150/Blender-For-UnrealEngine-Addons#46]
Hello I have been pulling my hair out for months now on this so here I go(and I do not particularly blame this plugin).

So I create a simple character in Makehuman(1.2 but the version does not matter tested current stable as well), select the Game Engine skeleton, export it as FBX units centimeter.

Go to Blender(2.82.7) clear the scene, import the FBX with scale 0.01 (working from clean project default settings) this imports the FBX,  ok and everything looks fine.

![Screenshot from 2020-03-03 15-26-45](https://user-images.githubusercontent.com/252905/75785178-9a4b6800-5d63-11ea-8372-91ae7f1b8456.png)

I export it to UE4 using this plugin(because I need to remove the double root bone). The only thing I check is Rotate Zero to fix a rotation of the mesh issue(the result is mostly the same with or without that option)

Import the exported FBX to the engine, select the mannequin skeleton and everything maps ok.

![Screenshot from 2020-03-03 15-27-54](https://user-images.githubusercontent.com/252905/75785238-b51ddc80-5d63-11ea-857f-cdf989996ab5.png)
(ignore the wrong texture)

**The issue**

After I switch the animation in the preview to anything the mesh gets morphed.

![Screenshot from 2020-03-03 15-30-29](https://user-images.githubusercontent.com/252905/75785401-f0b8a680-5d63-11ea-9316-0b5a35b7c8db.png)
(This is ThirdPersonRun)

Anybody knows?

Sad thing is that I know this worked before because I do have a working prototype but my note taking was weak and I failed to reproduce it the second time.

**Comment by aknarts** [comment]
Ok found the .blend file from when this worked to rule out Makehuman stuff... Did the export without changing any option imported again in the engine and the same issue.

**Comment by xavier150** [comment]
Hello Aknarts! I will try on my side, you can join me the .Blend File ?

In a recent version of my addon I corrected the problem of scale 0.01 which exists between Blender and Unreal, but you have to re-import the SkeletalMesh to have the same scale between the skeleton and the animation

**Comment by aknarts** [comment]
Here is the current blend file 

[male.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/4287424/male.zip)

And this is the blend from when I got it working I think they are mostly identical.
[MHTest.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/4287431/MHTest.zip)

I am on the latest version of the plugin because I saw some fixes that might have affected me but sadly no. I still fully expect this to be some issue between my keyboard and chair as I am a blender noob.

**Comment by xavier150** [comment]
I exported your skeleton with a animation test and everything seems working good with me.
I don't found animation in the blend file, you import the animation from another software ?
![Screenshot](http://xavierloux.com/sharex/UE4Editor_GtYxZZVXi2.jpg)

**Comment by aknarts** [comment]
Hey, if I add the animation in Blender I expect this to work just right. My issue is that if you in the plugin settings check "Remove root bone" this skeleton becomes Mannequin compatible or at least it should. But the animations from the default engine mannequin do not work.

**Comment by xavier150** [comment]
Oh you speak abour retargeting ? You don't have the same skeleton that why that don't work, not the same bone orientation or missing bone.
![Screenshot](https://i.imgur.com/QhsmyWf.png)

I don't use retargeting on my projects but if I follow this video https://youtu.be/4TrLiekYABY
I get this: ![Screenshot](http://xavierloux.com/sharex/RetargetFail_08.03.2020_1147.gif)

**Comment by aknarts** [comment]
No retargetting creates the issues that you have seen with the hands, back and such which is the main reason why I am trying to figure out how to do compatible skeleton import. 

Anyway I did some more testing and the issue has nothing to do with your plugin in particular so feel free to close it if you wish.

My workflow that I want to achieve is create a character in Makehuman -> Export to Blender -> Add some shape keys -> import to UE4 with the Mannequin skeleton(no retargetting needed). 

I must be missing something crucial in the steps so I am trying to recreate what I did half a year ago including all software versions to figure out how and what I am doing wrong. As for the skeleton in MakeHuman there is a supposedly UE4 compatible skeleton already in there so I need to test with that as well going from MH to UE4 directly to rule out Blender doing some shady stuff... I was just sort of hoping somebody to have some experience with this particular workflow. I will do some more tests and go to Unreal Forum directly for broader audience.

**Comment by aknarts** [comment]
Something that just hit me.. there is no "Pose" under what to export, and the MH files rely on pose quite a lot, it is what actually makes it compatible in a sense. Is that a feature that is missing as of now or is it merged into Animation?

**Comment by xavier150** [comment]
Hey @aknarts !
I published the new [update 0.2.8](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v0.2.8) 
So I close this issue :)
