### ISSUE TITLE
My Blender do not see addon 

### ISSUE THREAD

**Issue by Maximuz6** [xavier150/Blender-For-UnrealEngine-Addons#48]
After ''instal'' i do not see addon on the list((

**Comment by xavier150** [comment]
Hello! You downloaded from here ? https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases

**Comment by Maximuz6** [comment]
Wow! Now its fine! TNX!

**Comment by xavier150** [comment]
Yay ^^
