### ISSUE TITLE
Blender 2.8 Support

### ISSUE THREAD

**Issue by Rbn3D** [xavier150/Blender-For-UnrealEngine-Addons#5]
It's Blender 2.8 support planned for this script?

Blender 2.8 beta was recently released, and final version is planned for Q1 2019, so it would be be great to have this script ported to the new version.

Thanks!

**Comment by xavier150** [comment]
Hi Rbn3D,
Yes it is planned but I am overbooked so it will take a little time, I think less than 2 months !

**Comment by eobet** [comment]
I am testing the 0.2.2 version for 2.8, but the UI for the mod is placed under the T panel, which looks really weird in 2.8.

2.8 mods should be placed under the N panel.

**Comment by xavier150** [comment]
Yes, I will change that soon
