### ISSUE TITLE
Bug when exporting while in local view mode

### ISSUE THREAD

**Issue by andgeno** [xavier150/Blender-For-UnrealEngine-Addons#51]
When you export to UE4 while still being in local view mode all models to be exported will be moved to world origin **and** permanently stay there. You probably won't notice this until you exit local view mode. So there's quite a good chance you may have to start over and thus lose work - it happened to me many times now because I did not understand what triggered it.

**How to reproduce**
1. Add two or more objects into the scene and mark them for export to UE4 as usual.
2. Select one object and go into **local view mode** (`/` key).
3. Export using the `Blender for Unreal` add-on.
4. Exit **local view mode** and observe the issue sitting right there at the world origin. 😉

**Comment by xavier150** [comment]
Oh thanks for the report! I will correct in the next version :)

**Comment by xavier150** [comment]
Fixed: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/commit/018b33c4eede7c39fe223670d3a11a56319fc666
Now if you exporting in local view mode you will automatically return to the global view mode.
