### ISSUE TITLE
Bug Ver 2.8 bfu_WriteImportAssetScript.py  Forget to add ImportScript

### ISSUE THREAD

**Issue by gansaibow** [xavier150/Blender-For-UnrealEngine-Addons#56]
bfu_WriteImportAssetScript.py line:438 Forget to add ImportScript
"\t" + "unreal.EditorStaticMeshLibrary.remove_lods(asset)" + "\n"

Crash when running a script in UE4.

**Comment by xavier150** [comment]
Oh thanks! I just fixed and comit in the sources. That will be corrected in the next version  0.2.7.2

**Comment by gansaibow** [comment]
It's a great Addon, so please do your best. Thank you very much.
