### ISSUE TITLE
Exported skeletal mesh has low poly look

### ISSUE THREAD

**Issue by Qianfulong** [xavier150/Blender-For-UnrealEngine-Addons#58]
Hi,
first of thx for the amazing Plugin!
Now to the problem: When exporting s skeletal mesh along with it's animations all goes smoothly, however the mesh has that "low poly" look to it. When exporting the very same mesh via Blender FBX export the mesh looks normal. 

FBX Export:
![image](https://user-images.githubusercontent.com/6871003/84793566-903d3480-aff5-11ea-8468-f84db9724540.png)

Plugin Export:
![image](https://user-images.githubusercontent.com/6871003/84793636-a814b880-aff5-11ea-80c2-a5edb86d79ae.png)

I think when doing the normal FBX export the "Smoothing" option set to "Normals Only" is responsible for getting the high poly look in unreal while using "Face" would give the low poly look.
![image](https://user-images.githubusercontent.com/6871003/84793938-f75ae900-aff5-11ea-8df8-4410febafd0c.png)

So is there an option to export armatures/meshes with your plugin while getting the smoothed look in Unreal?

Cheers for your help on this!

**Comment by xavier150** [comment]
Hello!
I'm sorry I never saw your message notification. You still have the problem? 
My plugin export the skeletal mesh with Smoothing set on Face. If you still have the problem maybe you can send me the file I will try to reproduce on my side.
