### ISSUE TITLE
Scale and forward vector override options

### ISSUE THREAD

**Issue by taro8** [xavier150/Blender-For-UnrealEngine-Addons#6]
Could you please add an override options that would allow for exporting meshes without the need of rotating them 90* along the Z axis?
Also it would be nice to have a scale override as well.
With those 2 options things would be even easier to export.

**Comment by xavier150** [comment]
Hi Taro8,
You're right, I'll add his 2 options in an advanced option panel. I think release the next version at the end of February

**Comment by xavier150** [comment]
Hi Taro8, 
Why you want a option to turn the Z axis ? You can turn it directly into the blender scene, I wanted to add the fbx Axis Forward / Up option but this does not seem to work.
I have add the scale option but this is not recommended with the armatures
