### ISSUE TITLE
Sockets not importing

### ISSUE THREAD

**Issue by ridley075** [xavier150/Blender-For-UnrealEngine-Addons#60]
Used the tool to add a socket to the skeletal mesh, seems to be parented, has the right parent bone. Everything works well in Blender. But cannot get it to appear in unreal. Tried using the import asset script using unreal's now native python, as well as just manually importing them. Neither worked.

**Comment by xavier150** [comment]
Hello ridley075!
Socket importation is not yet supported with the native python integration.
You should use the 20Tab integration https://github.com/20tab/UnrealEnginePython 
[](url)
![20Tab](https://user-images.githubusercontent.com/7216958/86488995-2e096100-bd63-11ea-9db9-3f10a6162765.png)

But this integration no longer supports the latest versions of Unreal.

**Comment by saga-shumpei** [comment]
Hi Xavier,
I have just sent the blender file to your gmail.

Thanks, Shumpei

**Comment by xavier150** [comment]
If it doesn't work you can reopen this post
