### ISSUE TITLE
animation created with mixamo cannot be exported

### ISSUE THREAD

**Issue by saga-shumpei** [xavier150/Blender-For-UnrealEngine-Addons#63]
animation created with mixamo cannot be exported

Hello. First of all thank you for the very nice addon.

Now,I made a character with makehuman, imported it with blender, and then exported it with the extension fbx.
I uploaded that file to mixamo, set a running animation, and downloaded it.
I was able to run animation by opening the file with blender.

And I exported it with this addon. Then a subdirectory for animation should be created and fbx for animation should be created under it, but the subdirectory was not created and therefore fbx for animation was not created either. Do you know what?

Thank you.

**Comment by xavier150** [comment]
Hello Saga,
Your animation correctly detected in the export list?
![Export](https://user-images.githubusercontent.com/7216958/87242091-de452c80-c429-11ea-83e1-b90b77afb565.png)

You can chose what animation to export une Animation Properties Panel

**Comment by saga-shumpei** [comment]
My animations are not searched.
![capture1](https://user-images.githubusercontent.com/36815446/87249018-a07eed00-c497-11ea-95f0-0a0145b53a08.PNG)
Animation created with Mixamo seems to record to location instead of bone.
![capture2](https://user-images.githubusercontent.com/36815446/87249028-b391bd00-c497-11ea-90df-c0752ad7b402.PNG)
I'm not familiar with Python, but I managed to investigate.
As a result, I think TargetActionToExport.append is not executed because objBoneNames does not include 'Armature'.
![capture3](https://user-images.githubusercontent.com/36815446/87249052-d15f2200-c497-11ea-85cf-af0d5bef421f.PNG)

**Comment by xavier150** [comment]
You can send me the file? I will try on my side for found what wrong and
correct in next version

Le dim. 12 juil. 2020 à 16:33, saga-shumpei <notifications@github.com> a
écrit :

**Comment by saga-shumpei** [comment]
Hi Xavier,
I have just sent the blender file to your gmail.

Thanks, Shumpei

**Comment by xavier150** [comment]
Ok that now corrected thanks for the feedback!
Now this will detect the name of the bone in data_path of the fcurve and not in the channels name.

I think publish the release version 0.2.7.4 this weekend. Here is the beta build to correct this:
[blender-for-unrealengine - 2.8.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/4919233/blender-for-unrealengine.-.2.8.zip)

**Comment by saga-shumpei** [comment]
This worked correctly in my environment. With this, I can fine-tune the animation created with mixamo on blender and then bring it to the unreal engine.
I'm really thankful to you.

**Comment by xavier150** [comment]
Glad to hear! ^^
