### ISSUE TITLE
animations being exported broken

### ISSUE THREAD

**Issue by aleeckhart** [xavier150/Blender-For-UnrealEngine-Addons#65]
I am trying to export the animations of a model to unreal but they are all broken. As I am new to blender it may not be a problem with the plugin itself, but it would be wonderful if you could help me. I loved the plugin and everything, if every dollar in my country was not equivalent to a month of food, I would send you some for sure.

![Meu Vídeo](https://user-images.githubusercontent.com/68266272/87389226-badec680-c57c-11ea-8d7c-9d8d3440e1b6.gif)

[FPSarms.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/4916846/FPSarms.zip)
The zip file contains my blend if you need to test it

**Comment by xavier150** [comment]
Hello aleeckhart, thanks for the feedback!
I tested on my side and found the problem: With Unit Scale not at 0.01 my addon rescale the rig and anim curve but your armature use a scale of 0.128 so the resacale of anim curve is wrong. that now corrected!


I think publish the release version 0.2.7.4 this weekend. Here is the beta build to correct this:
[blender-for-unrealengine - 2.8.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/4919233/blender-for-unrealengine.-.2.8.zip)

**Comment by aleeckhart** [comment]
i teste it here and it's fixed, Thanks Xavier !

**Comment by xavier150** [comment]
Glad to hear! ^^
