### ISSUE TITLE
When exporting multiple animations, all animations are the same

### ISSUE THREAD

**Issue by AndresPiola** [xavier150/Blender-For-UnrealEngine-Addons#66]
When i export several animations, they are all the same. It doesnt matter how i set them, looks like it selects the last animation active in Action Editor but the rest is exported  as this one, but with their name. It's strange that the file size are different.

![image](https://user-images.githubusercontent.com/67182081/87457572-99122d80-c5d6-11ea-8083-fffaf451f165.png)

![image](https://user-images.githubusercontent.com/67182081/87457410-52bcce80-c5d6-11ea-8728-11fa0343d912.png)
![image](https://user-images.githubusercontent.com/67182081/87457861-16d63900-c5d7-11ea-9865-6a1f6ea09acb.png)
![image](https://user-images.githubusercontent.com/67182081/87457879-1f2e7400-c5d7-11ea-9b2b-6462fbc2e938.png)

**Comment by xavier150** [comment]
Hello Andres!
I get this error in a old version but it should be corrected now. You can
try in the last version ? If that doesn't work you can send me the file ? I
will try on my side and try to found the problem to correct it

Le mar. 14 juil. 2020 à 19:37, AndresPiola <notifications@github.com> a
écrit :

**Comment by AndresPiola** [comment]
With the latest v is fixed. thanks...but

**Comment by xavier150** [comment]
Yay ^^ but what ?

Le dim. 19 juil. 2020 à 10:30, AndresPiola <notifications@github.com> a
écrit :

**Comment by AndresPiola** [comment]
Strange. I was sure I posted a new issue regarding Rift animations
