### ISSUE TITLE
Animations made with rigify get distorted once exported to ue4

### ISSUE THREAD

**Issue by AndresPiola** [xavier150/Blender-For-UnrealEngine-Addons#68]
![image](https://user-images.githubusercontent.com/67182081/87879801-e7e70b00-c9ba-11ea-9ea3-800c1a0e703f.png)
![image](https://user-images.githubusercontent.com/67182081/87879812-f6cdbd80-c9ba-11ea-95af-b6d5bc0ef225.png)

**Comment by xavier150** [comment]
Hey, ^^
You can send me the model ?

**Comment by AndresPiola** [comment]
[
[Abutilon_RetopoFlow_AutoSave.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/4944359/Abutilon_RetopoFlow_AutoSave.zip)

](url)

**Comment by AndresPiola** [comment]
here you go. It's kind of messy because i was trying a lot of stuff to make it work so i hope it works for you

**Comment by Hard3D** [comment]
this issue inside of rigify: https://developer.blender.org/T57536

**Comment by xavier150** [comment]
Hey Andres, sorry for the delay. 
Yep I just test and that a rig problem. I have the same problem without the addon. 
The fbx file seem good but in unreal some rotations are fucked in interframe like when you pass from -180 at +180 in one frame


![InterframeBlender](https://user-images.githubusercontent.com/7216958/88110834-28a67600-cbad-11ea-9d9b-a42e0cbbdcc8.gif)
