### ISSUE TITLE
couldnt enable the plugin in the addon list

### ISSUE THREAD

**Issue by codehawk64** [xavier150/Blender-For-UnrealEngine-Addons#7]
registration error : object could not register

the above is the error when i click on the checkbox of the addon list for this plugin. For some reason i cannot enable it even though it seems to be installed. Tried whatever i can to fix this but couldnt find any solution. Can you tell me what might be causing this ? Thanks.

**Comment by xavier150** [comment]
Hi codehawk64,
Can you open the console and show me the python error? You work with what version of Blender ?
If this is an installation problem you can delete the folder blender-for-unrealengine in C:\Users\[YourUser]\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons

**Comment by hirschmannbenjamin** [comment]
same here, blender 2.8 

> bpy.context.space_data.recent_folders_active = 0
Modules Installed () from 'C:\\Users\\munka2\\Downloads\\blender-for-unrealengine.0.2.2c_Blender2.8.zip' into 'C:\\Users\\munka2\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
Traceback (most recent call last):
  File "E:\Blender2_8\blender-2.80.0-git.adfdae3fc2f4-windows64\2.80\scripts\modules\addon_utils.py", line 384, in enable
    mod.register()
  File "E:\Blender2_8\blender-2.80.0-git.adfdae3fc2f4-windows64\2.80\scripts\modules\bpy\utils\__init__.py", line 669, in register
    register_class(cls)
RuntimeError: Error: 'panel.bfu_pt_blenderforunreal' doesn't contain '_PT_' with prefix & suffix
bpy.context.area.ui_type = 'INFO'
>

**Comment by xavier150** [comment]
Hi hirschmannbenjamin, This is due to the new naming standards in Blender 2.8 with the last releases
I just updated with blender-2.80.0-git.adfdae3fc2f4 it should work now : https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v.0.2.2d

**Comment by hirschmannbenjamin** [comment]
Thanks, works like a charm.
