### ISSUE TITLE
Constraints are not baking in export (Blender 2.83)

### ISSUE THREAD

**Issue by Hard3D** [xavier150/Blender-For-UnrealEngine-Addons#70]
This is fundamental issue that push me to bake every animation manually.

I attach example file for testing. Note: Please choose **export only deform bones** 
[Addon_Issue_example.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/4953395/Addon_Issue_example.zip)

**Comment by xavier150** [comment]
Hello Hard3D,
Thanks for the feedback! The selected action was not the right one after the bake. That should work now.

I just publish the update: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases

**Comment by Hard3D** [comment]
Awesome work! Thank you so much! Now it's working brilliant! 
Epic Games released their addons for Blender, but it works not as expected. So please DO NOT STOP DEVELOP YOUR AMAZING TOOL!
