### ISSUE TITLE
Exporting/Importing LODs isn't working...

### ISSUE THREAD

**Issue by aprather51** [xavier150/Blender-For-UnrealEngine-Addons#71]
As much as I follow steps from this [Link](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/blob/master/Tuto/How%20export%20assets%20from%20Blender.md#level-of-details) and YouTube [2:11](https://youtu.be/YLOZZIlhgaM?t=131) for hours. Exporting LODs from Blender and Importing into UE4 don't seem to be working. The main asset does not recognize or change LODs from Static Mesh preview based on distance. Unless I've missed something?  How do I resolve this issue? 

Thanks in advance

Blender 2.83.2
UE4 4.25.1

**Comment by xavier150** [comment]
Hello aprather!
You can send me the file ? I will try to found what wrong tomorrow.

**Comment by aprather51** [comment]
Here's files in zip...

[Cliffs.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/4968550/Cliffs.zip)

**Comment by xavier150** [comment]
Hey ^^ I just tested, that work good on my side, you just need set the property for lods and expot like here
![image](https://user-images.githubusercontent.com/7216958/88336157-cd9f8b00-cd34-11ea-8205-f5310e102c08.png)
[How set for lod export video.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/4968632/How.set.for.lod.export.video.zip)

**Comment by aprather51** [comment]
After watching your video, I've started over and follow exact procedure you showed. The problem is within UE4, I think. I am unable to execute python script (ImportAssetScript.py) from console or nothing happened. After clicking on importAssetScript to copy and and pasted (ctrl +V) into console. Not even ImportedFBX folder or .fbx popped up into browser console.
Yep, The Python Editor Scripting and Sequencing plugin is enabled. 

BTW, I've updated 4.25.2 early today. 

![output_log](https://user-images.githubusercontent.com/10257247/88349263-34ad4780-cd15-11ea-94df-b8e95eadb1cc.jpg)
![plugin](https://user-images.githubusercontent.com/10257247/88349296-3b3bbf00-cd15-11ea-94ea-ab3432e128d0.jpg)

**Comment by xavier150** [comment]
Oh your script syntax is for 20Tab integration. In addon preference you
should uncheck 20Tab integration.

[image: 86488995-2e096100-bd63-11ea-9db9-3f10a6162765.png]

Then export and try again.

**Comment by xavier150** [comment]
Image:
https://raw.githubusercontent.com/xavier150/Blender-For-UnrealEngine-Addons/master/Tuto/ImportAssetDocVaniaPython.jpg

Le ven. 24 juil. 2020 à 09:34, xavier loux <xavierloux.loux@gmail.com> a
écrit :

> Oh your script syntax is for 20Tab integration. In addon preference you
> should uncheck 20Tab integration.
>
> [image: 86488995-2e096100-bd63-11ea-9db9-3f10a6162765.png]
>
> Then export and try again.
>
> Le ven. 24 juil. 2020 à 01:55, Arthur Prather, Jr <

**Comment by aprather51** [comment]
Now I see, 20Tab integration unchecked in addon preference, Imported cliffs in UE4,  I can now see all LODs from mesh preview. 

Thank you for your help and quick responses. Truly appreciate it, I will now close this.
