### ISSUE TITLE
Object data gets duplicated when exporting

### ISSUE THREAD

**Issue by rstolarski** [xavier150/Blender-For-UnrealEngine-Addons#72]
When exporting any object, it's mesh data gets duplicated.

I'm pretty sure object copying/duplicating is the intented way for this great plugin to work but in situation when I have to export multiple objects many times during a day, my blender file can get littered with unnecessary data.
Right now I don't have the solution to this problem other than playing it dirty and running **Purge All** command via `bpy.ops.outliner.orphans_purge()`.

I hope this gets fixed. Thank you for your time :grinning:

**How to reproduce**

1. Add any object to empty blender file.
2. Export using the `Blender for Unreal` add-on.
3. In `Blender File` tab in `Meshes` section data gets duplicated two times.

**Examples**
Before export
![obraz](https://user-images.githubusercontent.com/1962748/95019120-ea750a80-0663-11eb-9393-e445f7513ce6.png)
After single export
![obraz](https://user-images.githubusercontent.com/1962748/95019109-e21ccf80-0663-11eb-8fed-759cec9542c2.png)

**Comment by xavier150** [comment]
Hello Ryszard.

Thanks for the feedback!
Yeah my Addon do a duplication of the model with some edits I didn't think
of the additional data that this can create. I will look later and try to
fix it for 0.2.8 release. 😃

**Comment by xavier150** [comment]
Hey @rstolarski 

I fixed and just update the source files,  https://github.com/xavier150/Blender-For-UnrealEngine-Addons/blob/master/README.md#download-and-installation-from-sources

This will be included in the next version 0.2.8

**Comment by rstolarski** [comment]
@xavier150 New version from source files seems to be working correctly 💯

I think I've found yet another bug.  Documentation from here: https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-sources says:
`3. Compress "blender-for-unrealengine - 2.8" as new Zip file.`

However if I compress the directory with `- 2.8` at the end, addon would not install. It has to be the same name as it is in any other release - `blender-for-unrealengine`.
It shouldn't be a problem when releasing new version but it might be if someone wants to install from source files.

**Comment by xavier150** [comment]
Oh yes It's a mistake, I just corrected it, thanks! ^^

**Comment by rstolarski** [comment]
Thanks for the fixes 🥇
