### ISSUE TITLE
Save presets for import locations

### ISSUE THREAD

**Issue by hb20c** [xavier150/Blender-For-UnrealEngine-Addons#73]
Can you make it easier to save preset export/import locations? I noticed you save under Nomenclature you can set presets for names and export locations, however this doesn't include the Unreal Import locations. Every time I create a Blender project I have to set this myself, again and again. 

After trying out the "official" blender to unreal plugin, this one is WAY better. Thank you.

**Comment by xavier150** [comment]
Hello hb20c!

You right, I will add this for the next update, I'm doing some change on the UI to make the add-on easier to use.

In the meantime I have just corrected this and update the source files, https://github.com/xavier150/Blender-For-UnrealEngine-Addons/blob/master/README.md#download-and-installation-from-sources
Tell me if all work good

**Comment by hb20c** [comment]
Sorry to take so long to reply. I've tested it out and from what I can see, it's working perfectly now! Thanks!
