### ISSUE TITLE
Noise F-Curve modifier not being exported into Unreal Engine 4

### ISSUE THREAD

**Issue by zkm1** [xavier150/Blender-For-UnrealEngine-Addons#74]
I am using the latest updated Blender-For-UnrealEngine-addon version.

Error: The .FBX animation file imported into Unreal Engine 4 does not have the F-curve noise modifier added on from the graph editor from blender.

Blender's animation:
https://youtu.be/I7D7XwgDXxI

Unreal Engine 4's Import:
https://youtu.be/S_Dz4-m0Iek

The Unreal Engine 4's import lacks the jitter and noise from the Blender's animation.

Export Settings:
![image](https://user-images.githubusercontent.com/10038200/95788027-94b9e700-0c8f-11eb-9e93-4304cf23501d.png)

![image](https://user-images.githubusercontent.com/10038200/95788047-9edbe580-0c8f-11eb-8a06-6bce2ac51f7a.png)

![image](https://user-images.githubusercontent.com/10038200/95788079-a8fde400-0c8f-11eb-9687-a450620781f3.png)

![image](https://user-images.githubusercontent.com/10038200/95788111-b74c0000-0c8f-11eb-88f6-c0213cff1aee.png)

**Comment by zkm1** [comment]
![image](https://user-images.githubusercontent.com/10038200/95788237-fe39f580-0c8f-11eb-8290-9f6e8c07b4f1.png)
Here is what my Noise Modifier looks like

**Comment by xavier150** [comment]
Hello zkm1

Thanks for the feedback! Can you send me the model? I will try to reproduce the problem on my side: xavierloux.loux@gmail.com
While waiting if necessary the option "Bake Armature animation" In addon preference can help you

**Comment by zkm1** [comment]
It seems that once I exported with Bake Armature Animation, the problem was
fixed! Should I close this issue?

**Comment by xavier150** [comment]
Hey zkm1,

Thanks, I recevid and test! I know what the problem now: 
You using unit scale  at 1 and so my addon rescale your rig for Unreal Engine but don't rescale the modifier value so the F-Curve modifier are 100 times too small. That why that work with Bake Armature Animation. That will key all frame on the F-Curve before rescale.

I will try to fix for so as not to need bake and I will recontact you here

**Comment by xavier150** [comment]
Hey zkm1, ^^

I fixed and just update the source files, https://github.com/xavier150/Blender-For-UnrealEngine-Addons/blob/master/README.md#download-and-installation-from-sources

This will be included in the next version 0.2.8. Can you confirm to me that everything is working fine now wittout "Bake Armature Animation"?

**Comment by zkm1** [comment]
Hi!
The problem is fixed now!, It now imports correctly even without the bake
armature animation setting active.

**Comment by zkm1** [comment]
The problem is fixed now!, It now imports correctly even without the bake
armature animation setting active.
