### ISSUE TITLE
need multiple objects with same Socket names

### ISSUE THREAD

**Issue by PierrePS** [xavier150/Blender-For-UnrealEngine-Addons#75]
Hello there. I'm using this wonderful plugin for my Unreal projects. My problem is that I need multiple objects with the same socketnames on them. Due to blender not allowing you to have multiple objects having the same name I always end up with these funny little suffixes like ".001". Is there a way to split the socketnames at a certain character on export so "Socket.001" and "Socket.002" become "Socket" in UE? Or even to define the names for the sockets in a custom property? This would be really helpfull. :)

**Comment by xavier150** [comment]
Hello PierrePS!

Indeed this can be interesting. I will look to add properties like this in
sockets for the next versions. I will then contact you here.
Thanks for the feedback!

Xavier LOUX

**Comment by PierrePS** [comment]
Yay, thank you very much. You're a hero. AND a wizzard! :)

**Comment by xavier150** [comment]
Hey PierrePS! 

Thanks! I fixed and just update the source files, https://github.com/xavier150/Blender-For-UnrealEngine-Addons/blob/master/README.md#download-and-installation-from-sources 

![image](https://user-images.githubusercontent.com/7216958/96178733-1891fe80-0f30-11eb-9612-923526236970.png)


This will be included in the next version 0.2.8. Can you confirm to me that everything is working good?

**Comment by PierrePS** [comment]
Whow, that was quick! Just tested it with Blender 2.9. It works like a charme. Thank you so much. :)

Will this be available for Blender 2.7x as well? I'm still using that one most of the time out of habit.

**Comment by xavier150** [comment]
Nice thanks ^^
Sorry, I stopped development on Blender 2.7 The last version dates from 24 Jul 2019

**Comment by PierrePS** [comment]
All right. Then I will adjust myself to the new version. It's about time anyway. Thank you very much. :)
