### ISSUE TITLE
Import Asset Script no longer works in Unreal version 4.26.0

### ISSUE THREAD

**Issue by ZeroNRG05** [xavier150/Blender-For-UnrealEngine-Addons#77]
Using the **import asset script** in Unreal version **4.26.0** fails, producing this error:

LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "_myfolderpath_/ImportAssetScript.py", line 421, in <module>
LogPython: Error:     print(ImportAllAssets())
LogPython: Error:   File "_myfolderpath_/ImportAssetScript.py", line 16, in ImportAllAssets
LogPython: Error:     import ConfigParser
LogPython: Error: ModuleNotFoundError: No module named 'ConfigParser'

Some posts I found online claim **"configparser"** (all lowercase) is now used, so I tried simply replacing instances of "ConfigParser" with "configparser" in the script, but this only partially worked: While the Skeletal mesh now imported, animations did not.

The import script works perfectly in Unreal  **4.25.4**, so I assume Unreal **4.26.0** changed something.

**Comment by xavier150** [comment]
Hello, 
Thanks for the report! I just published a hot fix for Unreal Engine 4.26
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v0.2.7.5

**Comment by ZeroNRG05** [comment]
Perfect, that did it. Thanks for the quick fix.

P.S. In case anyone else still has this problem, the hot fix required a clean install of the add-on for me.
