### ISSUE TITLE
Blender 2.91 too slow and problem to import assets in Unreal Engine 4.26

### ISSUE THREAD

**Issue by dodolfo** [xavier150/Blender-For-UnrealEngine-Addons#78]
Hi.
I've seen the hotfix for Unreal Engine 4.26 and, as the title says, Blender became too slow when the Blender for Unreal Engine's Tool panel is displayed.
Also, after copy/paste the Python Script and run it on Unreal Engine Cmd console, nothing happens.
It's possible that I'm missing something?

**Comment by xavier150** [comment]
Hi dodolfo, 
Thanks for te report, The hotfix update should not have any impact on the performance, can you send me the file? I will try to see what is causing the problem and correct for the next version. 
I already working on some option of optimisation UI, You can try to if hide the tab with (N) so its should take no resources.

About Import Script with 4.26 you checked the installed plugins and execute type?
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/blob/master/Tuto/ImportAssetDocVaniaPython.jpg
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/blob/master/Tuto/ImportAssetDocVaniaPythonUseCmd.jpg

**Comment by dodolfo** [comment]
Hi xavier150.
Thanks for you response.
I tried your suggestions about checking the installed plugins and execute type. But for some reason, still nothing happens.
Here are the Blend. file and the screenshots about what's going on in Unreal Engine:
![screenshot](https://user-images.githubusercontent.com/74208042/102717246-d5e9fb00-42bf-11eb-8f4d-fe3dd4df97d0.jpg)
![screenshot2](https://user-images.githubusercontent.com/74208042/102717249-d7b3be80-42bf-11eb-8336-e9f4e5585822.jpg)

Note: I'm just trying to import an animated camera to Unreal Engine Sequencer. But I'm pretty sure that I'm missing something.

Blend File: 
[Camera.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/5721110/Camera.zip)

**Comment by xavier150** [comment]
Oh I do the hotfix only on assets parts, can you try this one ?
[blender-for-unrealengine(0.2.7.5)_Blender2.8.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/5721145/blender-for-unrealengine.0.2.7.5._Blender2.8.zip)

**Comment by dodolfo** [comment]
I tried this one that you sent me. But still nothing.
![screenshot3](https://user-images.githubusercontent.com/74208042/102718103-26b02280-42c5-11eb-912e-cf20053f4b7a.jpg)

**Comment by xavier150** [comment]
Oh I notice on the last screen you used 20Tab Format. The command should look like py "PATH" not  unreal_engine.py_exec(r"PATH")
In addon pref disable 20Tab and export again.

![image](https://user-images.githubusercontent.com/7216958/102718355-047bcc00-42e8-11eb-8684-0318c9c4889b.png)

**Comment by dodolfo** [comment]
Wow!! I disabled that option and now it's works perfectly! Thanks you very much!!
Kinds Regards!
