### ISSUE TITLE
Blender for Unreal Engine 4.26 exports Camera except rest of assets.

### ISSUE THREAD

**Issue by dodolfo** [xavier150/Blender-For-UnrealEngine-Addons#79]
Hi, xavier.
Sorry, it's me again.
But I tried to import a camera and many assets to Unreal Engine 4.26 sequencer and I get this console error:

Cmd: py "D:\Multimedia PRO\Desktop\MI SERIE\Personajes\ExportedFbx\ImportSequencerScript.py"
LogPython: Warning this file already exists
LogSlate: Window 'Save Asset As' being destroyed
LogPython: Sequencer reference created
LogPython: <Object '/Game/ImportedFbx/Sequencer/Escena1/MySequence.MySequence' (0x0000023893682400) Class 'LevelSequence'>
LogPython: ========================= Import started ! =========================
LogPython: Start import Camara
LogEditor: Attempting to add actor of class 'CineCameraActor' to level at -193.98,467.53,-355.06
LogPython: ========================= Imports completed ! =========================
LogPython: Camara
LogPython: =========================
LogLinker: Warning: Failed to load '/Game/ImportedFbx/Sequencer/MySequence': Can't find file.
LogLinker: Warning: Failed to load '/Game/ImportedFbx/Sequencer/MySequence': Can't find file.
LogUObjectGlobals: Warning: Failed to find object 'Object None./Game/ImportedFbx/Sequencer/MySequence'
LogPython: Error: D:/Multimedia PRO/Desktop/MI SERIE/Personajes/ExportedFbx/ImportSequencerScript.py:156: DeprecationWarning: AssetTools: Function 'open_editor_for_assets' on 'AssetTools' is deprecated: Please use UAssetEditorSubsystem::OpenEditorForAssets instead.
  unreal.AssetEditorSubsystem.open_editor_for_assets([unreal.load_asset(seqPath+'/'+seqName.replace('.',''))])
LogAssetEditorSubsystem: Error: Opening Asset editor failed because of null asset
LogEditorScripting: Warning: SyncBrowserToObjects. Cannot sync: /Game/ImportedFbx/Sequencer/MySequence
LogPython: Sequencer created with success !
![screen01](https://user-images.githubusercontent.com/74208042/102720792-36cffe00-42d5-11eb-8353-c2b8d2d3afc1.jpg)

It seems (at least for me) like some code of the current Unreal Engine version is deprecated.

**Comment by xavier150** [comment]
Hi Dodolfo ^^
Thanks for the report,

Try this, that should work better [blender-for-unrealengine_2.8.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/5721648/blender-for-unrealengine_2.8.zip)

The sequencer will be override on each import. I recommend to use a separate sequencer for your cameras. 
Like here: ![image](https://raw.githubusercontent.com/xavier150/Blender-For-UnrealEngine-Addons/master/Tuto/ImportAssetDocSequencerSeparateCamera.jpg)

So you can manage your assets in a sequencer and keep another sequencer to override for your cameras. (I just added this in doc)

But currently this ni only works with spawnable cameras, you will have to convert camera. so keep this Open I will comeback to you later.

**Comment by xavier150** [comment]
Hello @dodolfo !
Thank for your patience, I can work only on my free time for the moment.

I just published a pre release of the next version. https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/vp0.2.8 
You can try this version. everything should work fine now

**Comment by dodolfo** [comment]
Hello @xavier150 !
Great! I'm going to try this version right now!

**Comment by dodolfo** [comment]
Hi, @xavier150

Sorry for delay.
I was trying to deal with a problem about exporting a skeletal mesh with an animation from Blender to Unreal Engine. But I couldn't find any way achieve this because it throws this problem that I attach:

![capture00](https://user-images.githubusercontent.com/74208042/103088273-19e34580-45c9-11eb-95b9-6ac47c450b51.jpg)
![capture01](https://user-images.githubusercontent.com/74208042/103088274-1b147280-45c9-11eb-88cb-d6a33fbe1c90.jpg)

After this error, it duplicates all. From Blender's Scene, to the Rig and Meshes inside of Blend. file.

**Comment by xavier150** [comment]
Oh, you can send me the file ? I Will try on my side for found what wrong
You can send me file at
xavierloux.loux@gmail.com

About duplication that because the export process was stopped in middle.
During export my Addon will do a copy of the assets to export it then
remove the duplication.

**Comment by dodolfo** [comment]
I've sent you the Blend. file. In adittion, I'd like to show you something that I've found:
![problem](https://user-images.githubusercontent.com/74208042/103091786-0db0b580-45d4-11eb-83d6-5bc8f0d5079a.jpg)
It seems like I cannot import Animation Assets for some reason

**Comment by xavier150** [comment]
Hello @dodolfo !
I just tested the file you send if I use NLA I get the same error, that because Auto-Rig Pro don't support "Non Linear Actions"
I will hide this function when rig type is Auto-Rig Pro.

About Unreal Import I will test when I back to home in January.

**Comment by dodolfo** [comment]
Great! I'll be waiting! :)
Merry Christmas!

**Comment by xavier150** [comment]
Merry Christmas!

**Comment by xavier150** [comment]
Hello @dodolfo Happy new year ^^
Thank for your patience! I just published a new pre release: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/vp0.2.8.1 
You can tell me if all work good ?

**Comment by dodolfo** [comment]
Hello @xavier150  Happy new year ^^ !!
The first thing that I could note is that there is no NLA options. It could be great that exporting NLA anims could be possible. However (and maybe an unrelated question), it's possible to bake NLA Anims into a single Action? Because if it exists, I'd say that the addon it's perfect! =)

**Comment by xavier150** [comment]
Sadly natif NLA export are not supported by Auto-Rig Pro exporter. like you say I need do a bake and export like a single animation. That what I plan to do https://trello.com/c/sA3f332C/48-new

**Comment by xavier150** [comment]
I close this issues, I will look about NLA with Auto Rig after the next version
