### ISSUE TITLE
Multirig animations

### ISSUE THREAD

**Issue by RH2** [xavier150/Blender-For-UnrealEngine-Addons#8]
This may be more of a feature request*
Hi! this script is awesome.

Even though Actions can contain key-frames for multiple animations, the **NLA editor will only play one instance of the strip on one armature. This is a limitation with blender,** I think we need a list of virtual actions that links each armature to a sub action, and upon export all armatures are set to the appropriate sub-action.

When creating an action the script should know about the number of rigs:

**Creation:**
createAction(name, list of armatures) 
A constructor takes the desired name of a new action and the armatures to include in the animation.

**Sync:**
to make sure each armature is playing the correct animation, the user would select an action and press a button to set the active animation on the focused armatures. 

**Animation:**
While editing an action, it copies the key-frames to all other actions referencing the same master action. 

**Export**
A checklist of actions to export may include action1, action5, action6.
And the script would export: 

- armature1_action1,armature2_action1,armature3_action1
- armature1_action5,armature2_action5,armature3_action5
- armature1_action6,armature2_action6,armature3_action6

I would love to help implement this.

**Comment by xavier150** [comment]
Hi RH2 !
I'm not sure to understand but it looks like a novelty that I add for the
next version, It will be possible to export the animation NAL which will
take into account all the animation as it will play in Blender with the
transition and action layer.
Here http://xavierloux.com/sharex/blender_2019-02-11_00-31-46.jpg the NAL
Editor contains 4 actions in layer and it will be exported bake under a
single file with the name Anim_Flynt_Armature_NAL_animation.fbx of course
it will always be possible to export each action independently as before.

If the goal is to be able to change NAL animations in the same file I think
it would be easier to have several files for tre different animations
And about the actions that must be exported according to the frame you can
choose them in the animation properties like it
http://xavierloux.com/sharex/blender_2019-02-11_23-34-33.jpg
(Sorry for my english)

**Comment by RH2** [comment]
Hi Xavier,
Being able to utilize the NLA is great news! NLA is a solution, but I think the workflow could be simplified. Most of the time, game actions are short animations that are later combined by the games animation state machine. 

I thought I had solved the issue when I wrote this script:
```
action = bpy.data.actions["jump"]
bpy.data.objects["armature1"].animation_data.action = action
bpy.data.objects["armature2"].animation_data.action = action
bpy.data.objects["armature3"].animation_data.action = action
```
However, if I have constraints from armature3 to armature1,  that also has a constraint that depends on armature2. The exported animation may be broken even if it appears to be working in the viewport!

I think the solution may be automatically generating temporary nla strip setups at export time, creating and destroying the stack for each action. Would this be possible?

**Comment by xavier150** [comment]
I'm sorry I not sure to understand and I have a bad english :/
If I understand correctly you would like several states with for each state diferantes animations for the armature?

states 1: State1_Action1 on armature1, State1_Action2 on armature2, State1_Action3 on armature3
states 2: State2_Action1 on armature1, State2_Action2 on armature2, State2_Action3 on armature3
states 2: State2_Action1 on armature1, State2_Action2 on armature2, State2_Action3 on armature3

Then with blender to be able to select the desired state and export the all state for Unreal Engine ?

**Comment by RH2** [comment]
Yes, I think you get the idea.

There may be 4 animations: man_running, man_walking, backpack_running, backpack_walking.
If there are constraints, backpack_running will not export properly if it has constraints, and blender is evaluating man_walking. 

I think it's possible to select the desired set of animations to play automatically, using naming conventions or other methods. My hope is that the animator could expect things to be paired by default, and reduce some of the workload.

**Comment by xavier150** [comment]
Sorry for the delay, In your case I think the best would be to create several files for your animations with the NLA exports them use a extrenal script for export your all animation like it http://xavierloux.com/sharex/opera_2019-02-16_17-58-47.jpg

ExportAllAssets.cmd
```
"C:\YourPath\blender.exe" "C:\YourPath\man_running.blend" --background --python "D:\YourPath\Exportscript.py"
"C:\YourPath\blender.exe" "C:\YourPath\man_walking.blend" --background --python "D:\YourPath\Exportscript.py"
"C:\YourPath\blender.exe" "C:\YourPath\backpack_running.blend" --background --python "D:\YourPath\Exportscript.py"
"C:\YourPath\blender.exe" "C:\YourPath\backpack_walking.blend" --background --python "D:\YourPath\Exportscript.py"
```
Exportscript.py
```
import bpy
#Need Blender-For-UnrealEngine-Addons
bpy.ops.object.exportforunreal()
```

**Comment by RH2** [comment]
```
#ue4export header version 0.1  --back up your data before running, will overwrite file structure
#last tested with b-v2.79 ue4export-v0.2.1
import bpy
import datetime
S_time =  datetime.datetime.now()
print("---RUNNING-UE4  ::: "+str(S_time)+"---")

#list of actions
ActionList=[
'M4_ADS_RELOAD',
'M4_ADS_FIRE',
'M4_ADS_Transition',
'M4_hipFire',
'M4_hipFire2',
'M4_hipFire3',
'M4_hipFire4',
'M4_PoseLib',
'M4_putAway']

#list of armatures to include
ObjectList=[
'ARMS',
'AR_RIG',
'HELPER']


#context
original_context = bpy.context.area.type

#Remove all animation data (Clean Slate)
for rig in ObjectList:
	rigObj = bpy.data.objects[rig]
	rigObj.animation_data_clear()
    #bpy.data.objects[rig].animation_data_clear()

#Export one action set at a time
for focusedAction in ActionList:
    for rig in ObjectList:
        rigObj = bpy.data.objects[rig]
        for action in bpy.data.objects[rig].exportActionList: 
            action.use = False
            if action.name == focusedAction:
               action.use = True
               rigObj.animation_data_clear()
               rigObj.animation_data_create()
               actiondata = bpy.data.actions[focusedAction]
               if actiondata.users>1: #blender cannot play same animation on multiple rigs, so copies are made here
                  newAction = bpy.data.actions[focusedAction].copy()
                  newAction.name = focusedAction+' copy'+rig
                  actiondata=newAction
               rigObj.animation_data.action = actiondata
               ####Create NLA strips
               track = rigObj.animation_data.nla_tracks.new()
               newStrip = track.strips.new(actiondata.name, actiondata.frame_range[0], actiondata)
               rigObj.animation_data.action = None
               bpy.context.area.type = "NLA_EDITOR"
               bpy.ops.nla.actionclip_add(action=focusedAction)
               bpy.ops.anim.channels_clean_empty()
    bpy.ops.object.exportforunreal()

bpy.context.area.type = original_context 
```

Here is something that produces the result I was looking for, I create and destroy the nla strips dynamically, and also create copies of the original actions.
then I call your exportforunreal() function and everything pops out perfectly, and I don't need to split my animations into different .blend files.

**Comment by xavier150** [comment]
Oooh I see, nice job
