### ISSUE TITLE
Bad perfomance if scene contains a lot of armatures with actions

### ISSUE THREAD

**Issue by aftamat4ik** [xavier150/Blender-For-UnrealEngine-Addons#80]
This is old bug. If scene has 2 or 3 different armatures and you want to export one of them using BFU addon you will get huge lag. Addon will just freeze entire blender. 
This problem is caused by function:
bfu_Basics.py -> GetIfActionIsAssociated
which checks is action related to armature or not. Unfortunately there is no other way to perform this exact check. So that function can be optimised only by caching it's output. So i found a way to fix this bug by editing file: bfu_Utils.py
like that:
![pic1](https://user-images.githubusercontent.com/4356170/105412594-c828ec00-5c56-11eb-9472-abc3cca93741.PNG)

this is not perfect solution at all. Since i do it using global variables. But since my knowlege of python is very bad ... i don't have other options or ideas. So i can't commit it as a fork.

To give you better underestanding of this problem i recorded video on youtube: [link](https://www.youtube.com/watch?v=4ZF99MG-5Ns)

```
l_objn = ""
l_alist = []
def GetActionToExport(obj):
	#Returns only the actions that will be exported with the Armature
	
	global l_objn, l_alist
	
	if obj.ExportAsLod == True:
		return []

	TargetActionToExport = [] #Action list
	if obj.exportActionEnum == "dont_export":
		return []
		
	if obj.exportActionEnum == "export_current":
		if obj.animation_data is not None:
			if obj.animation_data.action is not None:
				return [obj.animation_data.action]
	
	elif obj.exportActionEnum == "export_specific_list":
		for action in bpy.data.actions:
			for targetAction in obj.exportActionList:
				if targetAction.use == True:
					if targetAction.name == action.name:
						TargetActionToExport.append(action)

	elif obj.exportActionEnum == "export_specific_prefix":
		for action in bpy.data.actions:
			if fnmatch.fnmatchcase(action.name, obj.PrefixNameToExport+"*"):
				TargetActionToExport.append(action)


	elif obj.exportActionEnum == "export_auto":
		#This will cheak if the action contains the same bones of the armature
		
		if(obj.name != l_objn):
			l_alist.clear()
			l_objn = obj.name
		
			objBoneNames = [bone.name for bone in obj.data.bones]
			for action in bpy.data.actions:
				if GetIfActionIsAssociated(action, objBoneNames) == True:
					TargetActionToExport.append(action)
					l_alist.append(action)
		else:
			return l_alist
	return TargetActionToExport

```

**Comment by xavier150** [comment]
Hey aftamat4ik,
Thanks I will look about and test this during this week end !

**Comment by xavier150** [comment]
Hey @aftamat4ik ,
I watched the video and updated my addon with a cache. (Dev branch) I will the next weekend publish a new Pre-release!
In the meantime here is the Dev build: [blender-for-unrealengine.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/5859908/blender-for-unrealengine.zip)

Tell me if everything is working fine.

**Comment by aftamat4ik** [comment]
hmm for some reason i can't download file you attached because of network error
![image](https://user-images.githubusercontent.com/4356170/105574163-89914f80-5d84-11eb-82b4-f342ec6cad6f.png)
so i can't check it. But there, probably, everything is ok so thank you for your attention.

**Comment by aftamat4ik** [comment]
finally it's downloaded. 
well... it's can't be enabled at all after reinstallation
![image](https://user-images.githubusercontent.com/4356170/105574484-b34b7600-5d86-11eb-997c-c19f187786c7.png)
![image](https://user-images.githubusercontent.com/4356170/105574493-c65e4600-5d86-11eb-849e-f8028641f1de.png)

**Comment by xavier150** [comment]
Hey @aftamat4ik 
I just tested the same file but that work on my side. You can try to remove the folder blender-for-unrealengine in C:\Users\BleuRaven\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons and test again

**Comment by aftamat4ik** [comment]
That worked. I completely removed old plugin's folder and tested. new interface looks kool. And it works a lot faster without any problems
![image](https://user-images.githubusercontent.com/4356170/105614553-f986f080-5deb-11eb-94ef-6122aefe499a.png)

for test purposes i exported this bow and now will test it in ue4 and in blender by importing fbx file into them
in blender after import it looks a bit strange but ok
![image](https://user-images.githubusercontent.com/4356170/105614611-45d23080-5dec-11eb-82c0-479d97c664d2.png)

during importing into ue4 i had little problem with animations here i had to change it from Exported time to Animated Time
![image](https://user-images.githubusercontent.com/4356170/105614722-dd378380-5dec-11eb-9e55-94598ee466c9.png)

But all works and all animations imported properly:
![image](https://user-images.githubusercontent.com/4356170/105614737-f8a28e80-5dec-11eb-8477-1c136e545f37.png)

physics asset is clean and perfectly scaled so it can be easily edited:
![image](https://user-images.githubusercontent.com/4356170/105614744-0c4df500-5ded-11eb-8182-a08d3dc5fbc9.png)
Even base material colors are set up properly. (anyway there was no textures)
![image](https://user-images.githubusercontent.com/4356170/105614759-2a1b5a00-5ded-11eb-9d8d-278145da7545.png)

This works. Thank you for your help!
