### ISSUE TITLE
Object name suffixes added regression?

### ISSUE THREAD

**Issue by gstorer** [xavier150/Blender-For-UnrealEngine-Addons#81]
I am having the problem described in #34 . The .001 suffixes are being added to my socket names. I was hoping I could work around this using the feature added in #75 . However, the dialogue box appears to have no effect. Perhaps the issues are related.

I am using release 0.2.8 preview 2 with Blender 2.91.2 and Unreal 4.26.0.

**Comment by xavier150** [comment]
Hello @gstorer 
Thanks for the report, I will try and fix this later when I have free time

**Comment by gstorer** [comment]
The 90 degree rotation for sockets also doesn't seem to be working. Three things related to sockets are probably related right?

**Comment by gstorer** [comment]
After a sleep I figured out the problem. I had all of my sockets prefixed with a lower case "socket_". If I replaced this with uppercase "SOCKET_" all seems to be well. I guess Unreal processes the lower case version while the script does not?

**Comment by xavier150** [comment]
Hey @gstorer 
Ooooh yeah, I make the buttons for set objects name with a specific prefix "SOCKET_" and so that applies change during export only in objects with this prefix. I will change this in the next version.

**Comment by xavier150** [comment]
Hey @gstorer I just published a new Pre-release !
That should be fixed now, tell me if all work good.
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases

**Comment by gstorer** [comment]
Yes this seems to have fixed the issue for me. Both the prefix Socket_ and socket_ seem to work now.

I got around to testing this as I was having another issue that seems semi-related: #84 .

**Comment by xavier150** [comment]
Thanks! that now fixed too in brache Dev.
