### ISSUE TITLE
Can't import anything (and I need to import an animated camera)

### ISSUE THREAD

**Issue by anechini** [xavier150/Blender-For-UnrealEngine-Addons#82]
I'm trying to import an animated camera from blender into unreal.
I don't know if I've got it wrong, but I'm creating MySequence before importing the camera from Blender. It gives me an error because the asset is already there and it is in use. So I try again after deleting it. The camera is created, but with no animation. A lot of error messages appears.
![blender for unreal error](https://user-images.githubusercontent.com/47920104/108288382-43ed5a00-716b-11eb-80c7-fcf0d7834be2.png)

**Comment by xavier150** [comment]
Hey @anechini !
You using the pre release version of the addon? This should be fixed, Now I'm using Json file for store data and not config file. 

If that don't work you can send me the Blender File? I will try on my side tomorrow.

**Comment by anechini** [comment]
Hi @xavier150 !
I'm using the Rev 0.2.7.5 (release 2.8, 2.9) with Blender 2.9.1.2 and Unreal 4.25.4.

[neoncity2.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/6003031/neoncity2.zip)

**Comment by xavier150** [comment]
Thanks, I will try when I back to home, You can try the Pre Rev 0.2.8.3 https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases That should work better. I will publish Rev 0.2.8 in March with all fix

**Comment by anechini** [comment]
I'll give it a try later! Thanks and please let me know if you find a workaround with rev 0.2.7.5.

**Comment by anechini** [comment]
Hey @xavier150 , I've tried rev 0.2.8.3... this is what I've got:
![blender for unreal error2](https://user-images.githubusercontent.com/47920104/108448822-31455480-7241-11eb-90fc-5aac3788b9c9.png)
maybe it is a configuration I have to do in unreal project settings?

**Comment by anechini** [comment]
in time... the camera data came from Pftrack and exported as DAE file to blender. Don't know if it is important.

**Comment by xavier150** [comment]
Hey @anechini 
I did not get the time for test. I will test tonight (around 15h hours for me)

**Comment by xavier150** [comment]
Hey @anechini  Hum you send me a .uproject file but I need a .Blend file

**Comment by anechini** [comment]
[pftrack-blender-aprox2.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/6012326/pftrack-blender-aprox2.zip)
Sorry! Here it is!

**Comment by xavier150** [comment]
I found! In you scene you not set the camera as exportable. You need set 'Export recursive' on the all root objects you want to export. My addon will export only these objects
![image](https://user-images.githubusercontent.com/7216958/108553075-783f5280-72f2-11eb-9f8b-eda6404fcf05.png)

You have more info in doc
[Doc 1/2](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/blob/master/docs/How%20export%20assets%20from%20Blender.md)
[Doc 2/2](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/blob/master/docs/How%20import%20assets%20from%20Blender%20to%20Unreal.md)

I will add a warning for avoid code error

**Comment by anechini** [comment]
Hey @xavier150 , thank you very much! Actually I was doing it right, using the export recursive option. I've just found out the trouble was with the 4.25 version of Unreal. I installed the 4.26 version yesterday and it worked like a charm. 
I haven't change anything in settings, so I still don't know why it doesn't work with 4.25v.

Well, now I'm going to use the 4.26v. Thanks for your help!

**Comment by xavier150** [comment]
Oooh ? Thanks for the info I not tested with 4.25 will try too

**Comment by xavier150** [comment]
Hey @anechini I published the new [update 0.2.8](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v0.2.8) 
So I close this issue :)
