### ISSUE TITLE
Collision meshes getting .00x numbers added to their name if the parent mesh also has a socket.

### ISSUE THREAD

**Issue by gstorer** [xavier150/Blender-For-UnrealEngine-Addons#84]
I have found my collision meshes are getting .00x numbers added to their name if the parent mesh also has a socket. This means Unreal does not detect them as valid collision meshes as they don't match the parent name correctly.

To make this happen, the parent mesh needs to have had the socket(s) added before the collision mesh(es), if you add them afterwards things seem to be OK. Also, if I rename the sockets so they are prefixed with socket_ or Socket_ it also works OK.

Example of the issue with a simple cube and sphere:
https://we.tl/t-MSVmHsEVnk

I am using release 0.2.8.3 with Blender 2.91.2 and Unreal 4.26.1.

**Comment by gstorer** [comment]
This also seems to happen without sockets if you add multiple collision meshes, the additional meshes will also have the wrong name.

**Comment by xavier150** [comment]
Hey @gstorer ,
Thanks for the report! I fixed this too and Push the brache Dev, I will soon update the addon.

**Comment by gstorer** [comment]
Thanks, the version in the dev branch has fixed it for me :)

**Comment by xavier150** [comment]
Hey @gstorer I close this issue too ^^  [update 0.2.8](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v0.2.8)
