### ISSUE TITLE
FeatureRequest : About Importing Camera

### ISSUE THREAD

**Issue by grimask4496** [xavier150/Blender-For-UnrealEngine-Addons#87]
1.Currently, camera keyframes are baked to all frames. Can this be a bake to a specific key only?

2.The imported camera is imported as "Possessable" in the sequencer now, but I think it's better to make it "Spawnable". This is because "Possessable" will spawn unnecessary cameras on the level.

![ExportCamera](https://user-images.githubusercontent.com/34054236/109167444-1df63400-77c1-11eb-9bd3-19df9b766015.png)

**Comment by xavier150** [comment]
Hey @grimask4496 ,
You right, that what I do in the next version. you can try the preview release the cameras are imported as "Spawnable"
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases Pre Rev 0.2.8.3

About the bake this is to be sure that the movement is exactly the same in Blender and Unreal Engine. Animation curves are not evaluated in the same way in Unreal and Blender and it is also necessary to take into account that the camera could be controlled without animation keys for example animated with a Rig

**Comment by grimask4496** [comment]
OK! Thank you.

Personally, if the number of keys matches, I think it will be easier to make adjustments animation on UE4.
At least, it is useful to have the option to match only the keys, even if the curves are different.

**Comment by xavier150** [comment]
Indeed, I note this for after the next version.
https://trello.com/b/32g729kg/bfu-blender-for-unreal-engine-addon

**Comment by xavier150** [comment]
Hey @grimask4496 I published the new [update 0.2.8](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v0.2.8) 
So I close this issue :)
