### ISSUE TITLE
Feature Request: Collection Name to Subfolder

### ISSUE THREAD

**Issue by HatiEth** [xavier150/Blender-For-UnrealEngine-Addons#90]
When dealing with large blender files and a lot of small props it might be useful to auto-set the Subfolder name to the wrapping Collection. This also might be recursive meaning Collection A/B would be Subfolder A/B as those already seem to work.

**Comment by xavier150** [comment]
Hello @HatiEth ,
That a good idea! I added this option for collection and push in the Dev Branch. You can now select an collection and set the SubFolder. 
![image](https://user-images.githubusercontent.com/7216958/110123212-e723ad80-7dc0-11eb-89b3-94f0ba4ce061.png)

I will soon publish a this update. then I will add more option about collection like for static mesh after the next update.

**Comment by xavier150** [comment]
Hey @HatiEth I published the new [update 0.2.8](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/v0.2.8) 
So I close this issue :)
