### ISSUE TITLE
Having trouble with scale

### ISSUE THREAD

**Issue by kevinbgood** [xavier150/Blender-For-UnrealEngine-Addons#93]
I'm trying to export a camera track (matchmove from live action camera) into Unreal. It seems the scale is getting thrown off.

e.g. In blender I have a box that's < 2m across. My Scene Properties > Unit Scale is set to 0.01. So when I measure things in Blender they seem about right. But then in Unreal it's 100x scale.

Thanks for any ideas!

[blendertrack-04-kevin_scales.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/6402960/blendertrack-04-kevin_scales.zip)

**Comment by xavier150** [comment]
Key @kevinbgood!
Thanks for the freeback, 
I did not manage to reproduce the error, for my part the result is the same from Blender to Unreal Engine.

I only set in Unreal Engine the FStop limit to 1000 for remove the blur.
![F-Stop limit Blur](https://user-images.githubusercontent.com/7216958/116703454-98625080-a9ca-11eb-82b3-659f020ff54e.jpg)

This is what I have
![Frames](https://user-images.githubusercontent.com/7216958/116704379-9baa0c00-a9cb-11eb-86f5-5a0230c1a7f4.jpg)

I noticed that you have disabled the export of additional data files, the camera position information is stored here. So I think the script is using an old version. check this and test again.

![Additional data](https://user-images.githubusercontent.com/7216958/116705416-cea0cf80-a9cc-11eb-9b3f-c9ef0b9830e6.jpg)
