### ISSUE TITLE
Scaling Issue on SKM Export

### ISSUE THREAD

**Issue by gradgr** [xavier150/Blender-For-UnrealEngine-Addons#94]
Scaling Issue on SKM Export.
-Using default Metric 1.0
-Default Addon Preferences
-Armature and mesh scale 1.0
-No animation

Simple basketball net object parented with a single bone root. Once exported i get this error, if i try export this again, it exports, but importing it to ue4 its on scale 1 but actually the proportion are like 0.01 , like the Auto-Scale doesnt work, and apart from that it changes the Metric on Blender to 0.01 without reverting it back to where it was before (1.0)

![a1](https://user-images.githubusercontent.com/12486207/116978963-14131480-accd-11eb-91d5-19f7435bc77b.jpg)
![2](https://user-images.githubusercontent.com/12486207/116978970-16756e80-accd-11eb-8cbd-b0490fac2e93.PNG)
![3](https://user-images.githubusercontent.com/12486207/116978981-183f3200-accd-11eb-90fe-339aafabf909.PNG)

**Comment by xavier150** [comment]
Hey @gradgr ,
Thanks for the report, I found and fixed the issue!

I updated the sources in dev Branch: https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch

Try with the Dev Branch If it works you can close the issue and if not send me the file.

**Comment by gradgr** [comment]
Great that indeed fixed it. Thank you mate! :-)
