### ISSUE TITLE
Blender bug report

### ISSUE THREAD

**Issue by DanielOrtizApoloFilms** [xavier150/Blender-For-UnrealEngine-Addons#95]
Hello¡
First of all thanks for your work, I'm trying to export a camera and these are the mistakes that pop up, any ideas?
Thanks again for your effort.
![Captura de pantalla 2021-05-04 124502](https://user-images.githubusercontent.com/83635961/116992590-905e2580-acd6-11eb-9df8-55e36fc3f9f0.png)

**Comment by xavier150** [comment]
Hey @DanielOrtizApoloFilms !

Thanks for the report, I found and fixed this issue.

I just updated the sources in dev Branch: https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch

Try the Dev Branch and if it works you can close the issue.

**Comment by DanielOrtizApoloFilms** [comment]
Thanks xavier¡¡¡¡
