### ISSUE TITLE
"Traceback (most recent call last)" When trying to export a skeletal mesh

### ISSUE THREAD

**Issue by RecklessJames** [xavier150/Blender-For-UnrealEngine-Addons#97]
Using this addon for the first time and decided to see if it was better than the regular method of exporting into UE4. Exporting static meshes seem to work fine, but when trying to export a skeletal mesh then I get this error.

![2edd5e46bc359c99ed9bb411be78d3ea](https://user-images.githubusercontent.com/12752293/121062994-c5590e80-c793-11eb-8bf0-5b485f1de47f.png)
![bdd10cc3bc5d0332c1808bce81db1a02](https://user-images.githubusercontent.com/12752293/121062951-ba9e7980-c793-11eb-9587-40d8e5010c76.png)

I'm not sure if I did anything wrong or not, but either way I would greatly appreciate any help, thanks!

Edit: Btw I am using version 2.8 for Blender 2.8

**Comment by xavier150** [comment]
Hey @RecklessJames !
This error has fixed for the next release. Try the Pre-release and tell me if you still have the issue. https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/vp0.2.9.1

**Comment by RecklessJames** [comment]
Yup its still giving the same issue, I tried it out just now.

**Comment by xavier150** [comment]
Hey @RecklessJames you can send me the file ? I will try to found what wrong here or at xavierloux.loux@gmail.com for private files.

**Comment by RecklessJames** [comment]
All it is was simply just the basic default Mannequin exported straight from UE4, but sure I'll email soon when I get the chance.

**Comment by xavier150** [comment]
Hey @RecklessJames That an error from my part. I published a new Pre-release. You can try this version ?
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/releases/tag/vp0.2.9.2

The issue was: "Export SkeletalMesh without animation_data make script fail."

**Comment by RecklessJames** [comment]
I was able to export a .fbx without issue, no more errors. I have not tested how it'll go when bringing it into UE4 yet, however. So I will test that soon today and I'll let you know how it goes.

**Comment by RecklessJames** [comment]
Update to this, it doesnt work when trying to import into UE4.

![e407ddcdbccc400862e3d2c971963eee](https://user-images.githubusercontent.com/12752293/122461040-d6b6cd80-cf80-11eb-9bc5-6650e7d743f4.png)

I never get this problem at all when I export/import .fbx files the old fashioned way. Again, this is using the default mannequin skeletal mesh without being altered, and the same file I would normally use for testing that works when doing regular importing.

**Comment by xavier150** [comment]
Hey @RecklessJames
This is because your skeletal mesh have several root bone and Unreal support only one root bone.
Without my addon when import a skeletal mesh with "Armature" name Unreal with create a new root bone. This is wrong and produce physics errors.

![image](https://user-images.githubusercontent.com/7216958/122464067-adb12f80-cfb6-11eb-865e-ed63c9d8d619.png)
![image](https://user-images.githubusercontent.com/7216958/122464201-df29fb00-cfb6-11eb-8e01-5554196d0135.png)

Add a new bone, name it root and attach the bones pelvis, ik_foot_root and ik_hand_root

**Comment by xavier150** [comment]
Hey @RecklessJames 
How is it going now ? ^^ You can close this issue if everything is working fine.

**Comment by RecklessJames** [comment]
No the issue was never fixed, and also saying what I did is "wrong" is an incorrect statement as I have already mentioned that it imports perfectly fine by itself without the addon.

**Comment by xavier150** [comment]
Your armature have several root bones as specified in the error in Unreal Engine.
"Multiple roots are found in the bone hierarchy. We only support single root bone."

So use only one root bone and that should be fixed. You have this error too without my addon when you export an armature with the name "Armature" and multiple root bones.
![image](https://user-images.githubusercontent.com/7216958/122464201-df29fb00-cfb6-11eb-8e01-5554196d0135.png)

**Comment by xavier150** [comment]
I updated the doc with more info about root bone: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/How-avoid-potential-errors#multiple-root-bones
