### ISSUE TITLE
Instanced Collections do not export properly

### ISSUE THREAD

**Issue by TrillNeato** [xavier150/Blender-For-UnrealEngine-Addons#99]
First off thanks for writing this addon, I use it religiously.

Collection instances are not being exported properly, they seem to ignore final location and rotation (also parent hierarchy it seems). Steps to amend this should be Make instances real and apply visual geometry to mesh. This is the current work-around but hinders non-destructive workflow.

**Steps to recreate:** 
1. Create a collection and place an object to be instanced.
2. Create a collection to designate as export and add numerous Collection Instances inside pointing to collection in first step.
3. Under Export section in addon panel, choose Collection(s), choose 'Scene' at top of panel and choose collection you've designated for export under collection list.
4. Upon export the FBX does not preserve transformations on collection instances and results in discrepancies.

**Workaround:**
CTRL+A the collection instances and make instances real, CTRL+A and apply visual geometry to mesh before exporting.

**Images**
![image](https://user-images.githubusercontent.com/7545197/122818069-bd768f80-d2a6-11eb-91ad-c0ff8c1bce2a.png)
![image](https://user-images.githubusercontent.com/7545197/122817363-d0d52b00-d2a5-11eb-8fc9-cf65a2fd867c.png)
![image](https://user-images.githubusercontent.com/7545197/122817429-e185a100-d2a5-11eb-991d-e5da972c30e6.png)

Thanks for putting this together, would appreciate a fix.

**Comment by xavier150** [comment]
Hey @TrillNeato ,
Thanks for the report! I have difficulty recreate the problem, you can send me the file? I will try to found why that don't export properly. Xavierloux.loux@gmail.com

**Comment by TrillNeato** [comment]
Hello @xavier150, thanks for the reply! I've sent the stripped down file to your inbox.

Much appreciated

**Comment by xavier150** [comment]
Hey @TrillNeato ^^
I will update the new version for the next week.
If all work good now you can close this issue.

**Comment by TrillNeato** [comment]
Hi @xavier150,

I have tested this pre-release and it appears to has resolved the issue. I can use instanced collections freely with the exporter now :)

I will mark closed assuming this remains fixed in future versions.

Thanks so much!

**Comment by TrillNeato** [comment]
Hi @xavier150 

It appears as though this change may have broken collision exporting, I am unable to see my UCX collision in simple collision upon import. The actual mesh shows up in the  This may be due to the altering of hierarchy created by this change. I am reopening this issue.

![image](https://user-images.githubusercontent.com/7545197/124517033-fb001000-ddb0-11eb-9cb0-e50d4a02a145.png)
![image](https://user-images.githubusercontent.com/7545197/124517065-03f0e180-ddb1-11eb-8940-cad863572bec.png)

**Comment by TrillNeato** [comment]
Here's a slice of the exported mesh hierarchy.
**
![image](https://user-images.githubusercontent.com/7545197/124517214-6d70f000-ddb1-11eb-9c48-57c5fb00c68c.png)
**

**Comment by xavier150** [comment]
Thanks for the report @TrillNeato ! Currently I can not work on the addon, will look about when I back to home in 8 days and recontact you.

**Comment by TrillNeato** [comment]
Kind of noticed something myself, even earlier revisions demonstrate the same issues with collision not being recognized. I think it has everything to do with the names that are created as a result of duplicating the objects. In some cases the UCX won't be renamed too drastically and in other cases it gets truncated/obfuscated.

![image](https://user-images.githubusercontent.com/7545197/125812626-e9fe972c-74b2-4508-b216-76b2e571c83b.png)

Is there a way to rename the original objects in the collection with a temporary name in order to duplicate out the set + export it while keeping the original naming conventions?

**Comment by xavier150** [comment]
Hey @TrillNeato,
Thanks for the help! I changed the export method for collection. That not finished but that should work a lot better for collision and instances in collections.
I updated the dev Branch: [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch)

**Comment by TrillNeato** [comment]
Many thanks, I'm looking over it now.

**Comment by TrillNeato** [comment]
Alright so the naming conventions are retained so UCX, Sockets, and mesh hierarchy is preserved on import which is great. But in blender outliner every time an instanced collection is exported it adds a blank empty for every instanced collection. Which is not ideal.

![image](https://user-images.githubusercontent.com/7545197/126215180-2fa5065a-3aa7-4e26-80e2-dce0fc2205f7.png)


Every export will do this so your collection will grow and grow with useless empties. Probably a cleanup step should resolve.

**Comment by TrillNeato** [comment]
Hi @xavier150, everything I'm seeing seems to be working as intended. My only complaint is exports can be a little sluggish at times but if the addon works from this point forward I think this issue is in the bag, thanks! :)

**Comment by xavier150** [comment]
Thanks to you for the report and help :)

**Comment by StrykeDev** [comment]
It seems like it broke again in 4.4.8 (Blender 5.2.0 LTS)
It no longer exports collection instances, except for linked collections, and it doesn't move the instances to the origin.

Use this [test file](https://github.com/user-attachments/files/31417853/BFUE_Issue.zip) with default settings to recreate the issue.

This is what I got:
<img width="1005" height="792" alt="Image" src="https://github.com/user-attachments/assets/9dd00b96-2d60-4c83-960c-55459be5d1c6" />

**Comment by xavier150** [comment]
Hey @StrykeDev,
I was able to reproduce both issues, and I have now fixed them. They were related to the Make Instances Real function.

<img width="584" height="525" alt="Image" src="https://github.com/user-attachments/assets/9e0206e2-a3c3-494c-a7ca-a760f701172b" />


I have updated the dev branch: https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/Download-And-Installation-From-Dev-Branch

Thanks for the report and the file!
By the way, If I don't get the notification I will be unware of the issue. So please open a new issue next time. :3
